### ISSUE TITLE
device reminder "Terminated (UNCAUGHT_EXCEPTION): Without reason"

### ISSUE THREAD

**Issue by sebingel** [Xenon-s/ioBroker.device-reminder#103]
**Describe the bug**  
Device (washing machine) start was registered at 08:48 and pushover message was sent. But device stop was never sent.
Log says
```
device-reminder.0 | 2021-07-26 09:40:27.448 | info | (16083) Device "Trockner" was successfully created
-- | -- | -- | --
device-reminder.0 | 2021-07-26 09:40:27.375 | info | (16083) Device "Geschirrspühler" was successfully created
device-reminder.0 | 2021-07-26 09:40:27.160 | info | (16083) Device "Waschmaschine" was successfully created
device-reminder.0 | 2021-07-26 09:40:27.027 | info | (16083) starting. Version 1.2.9 in /opt/iobroker/node_modules/iobroker.device-reminder, node: v12.22.2, js-controller: 3.2.16
device-reminder.0 | 2021-07-26 09:39:53.920 | warn | (13270) Terminated (UNCAUGHT_EXCEPTION): Without reason
device-reminder.0 | 2021-07-26 09:39:53.918 | info | (13270) terminating
device-reminder.0 | 2021-07-26 09:39:53.843 | error | (13270) device.dateJSON.push is not a function
device-reminder.0 | 2021-07-26 09:39:53.842 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
device-reminder.0 | 2021-07-26 09:39:53.842 | error | at runMicrotasks (<anonymous>)
device-reminder.0 | 2021-07-26 09:39:53.842 | error | at deviceReminder.getValues (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:623:20)
device-reminder.0 | 2021-07-26 09:39:53.842 | error | at deviceReminder.evaluateStatus (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:754:29)
device-reminder.0 | 2021-07-26 09:39:53.842 | error | (13270) TypeError: device.dateJSON.push is not a function
device-reminder.0 | 2021-07-26 09:39:53.839 | error | (13270) unhandled promise rejection: device.dateJSON.push is not a function
device-reminder.0 | 2021-07-26 09:39:53.821 | error | (13270) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
```

**To Reproduce**  
I did not try to reproduce it yet. But I will report if it happens again.

**Expected behavior**  
device reminder should notify me about the deivce in case it finishes

**Screenshots & Logfiles**  
![Screenshot 2021-07-26 125258](https://user-images.githubusercontent.com/3743705/126977764-184624cc-2f33-4173-ad85-45b031a175b0.png)

**Versions:**  
 - Adapter version: 1.2.9
 - JS-Controller version: 3.2.16
 - Node version: v12.22.2
 - Operating system: Raspberry Pi OS

**Additional context**  
Let me know of you need any more detail of my configuration

**Comment by sebingel** [comment]
Looks like a general issue.
Just reproduced with a different device (dryer).

![grafik](https://user-images.githubusercontent.com/3743705/126992332-9f3dc46f-9105-4d8f-a85e-f663148f8331.png)

**Comment by Xenon-s** [comment]
Please delete the "Last Operations" data point and then restart the adapter. Without deleting the datapoint I cannot fix the problem. But I leave this to the user and do not do it automatically, because then there could be problems in VIS or scripts.
If there are any other problems, please let me know.

**Comment by Xenon-s** [comment]
@sebingel 
I need a screenshot of the content of the data point "last Operations". Please from the whole content!

**Comment by sebingel** [comment]
I already downgraded to Version 1.2.3 which was the last version I used before the update.

I will update again and provide the screenshot a soon as I run into this problem again.

**Comment by sebingel** [comment]
I updated to Version 1.2.9 again and was able to reproduce the error.
![grafik](https://user-images.githubusercontent.com/3743705/127864378-6d7669a5-e985-4401-8a8b-88a014494da0.png)
Content of "last Operations" for this device is as follows:
`{"startVal":"27.07.2021 08:35:43","end":"27.07.2021 09:08:53","runtime":"00:33:00"}`
![grafik](https://user-images.githubusercontent.com/3743705/127864781-b63ccd7f-742b-4780-b2f5-4fe42e3b59f2.png)

**Comment by sebingel** [comment]
And again:
![grafik](https://user-images.githubusercontent.com/3743705/127878553-96005424-a8a7-4238-8af4-8733dabbcbdd.png)

The content of "last Operations" did not change:
`{"startVal":"27.07.2021 08:35:43","end":"27.07.2021 09:08:53","runtime":"00:33:00"}`

![grafik](https://user-images.githubusercontent.com/3743705/127878621-f46ae3c2-32e7-4da2-a656-661c7c13176e.png)

**Comment by Xenon-s** [comment]
Please delete the datapoint and restart adapter

**Comment by sebingel** [comment]
That helped. Thank you.
