### ISSUE TITLE
Meldung kommt mehrmals

### ISSUE THREAD

**Issue by Stevelande** [Xenon-s/ioBroker.device-reminder#125]
**Describe the bug**  
Es kommen die Meldungen immer doppelt selbst wenn die Maschine nicht lief 4:46 Uhr.Man beachte den 04.10. Welche Einstellungen soll ich ändern um das Fehlverhalten zu beenden?

**Screenshots & Logfiles**  
![Screenshot_2021-10-06-14-46-09-286_org telegram messenger](https://user-images.githubusercontent.com/26803698/136205325-48e4d8aa-f2fb-4efa-bb98-8e5047c636a1.jpg)

**Versions:**  
 - Alle Versionen sind aktuell

**Comment by Xenon-s** [comment]
Es wird gestartet erkannt, das bedeutet das deine Schwellwerte falsch eingestellt sind.
Schau mal in den Datenpunkt "average consumption", da steht dein aktueller Durchschnittsverbrauch. Überschreitet er deinen schwellwert so oft, wie eingestellt, wird gestartet erkannt. Wird er dann in Folge wieder unterschritten, kommt die Ende Meldung.

Wie viel Watt zieht deine Maschine im Standby?

**Comment by Stevelande** [comment]
Das kann ich heute Abend sagen. Ich habe erstmal alle Einstellungen gelassen wie sie waren. D.h. 15W ist der Schwellwert. Denke nicht das die Maschine im Standby mehr als 15W zieht.
 Ich sollte mal ein Waschprogramm Logen!
