### ISSUE TITLE
JSON Table in VIS

### ISSUE THREAD

**Issue by RoboCop0815** [Xenon-s/ioBroker.device-reminder#126]
Moin Moin 
Die Daten aus "device-reminder.0.Spülen.last operation" funktioniert in den Vis JSON Table so lange bis sich 10 Datensätze "reingeschrieben" haben, danach kommen keine neuen hinzu und dadurch habe ich keine Neuerungen in meinen Tabellen.
Die installierte Version ist die 1.2.9
würde mich über eine schnelle Lösung freuen.
Grüße Robbie

**Comment by Xenon-s** [comment]
Eigentlich ist es so das immer der älteste Eintrag gelöscht und der neuste hinten angehangen wird. Ist das bei dir nicht der Fall?

**Comment by RoboCop0815** [comment]
Nein leider nicht ... ich dachte es wäre so, aber er macht es nicht...-- Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 09.10.21, 15:08 schrieb Xenon-s ***@***.***>:

   
  Eigentlich ist es so das immer der älteste Eintrag gelöscht und der neuste hinten angehangen wird. Ist das bei dir nicht der Fall?

**Comment by Xenon-s** [comment]
Ich schau es mir mal an. Aktuell bin ich unterwegs, kann also ein paar Tage dauern..

**Comment by RoboCop0815** [comment]
@Xenon-s gibt es schon etwas neues wegen meine Anfrage?
Grüße Robbie

**Comment by Xenon-s** [comment]
nein, gibt nichts neues

Ich bin bereits mit der neuen 2.0 angefangen und entwickle die 1.x nicht mehr weiter. Auch keine Bugfixes, die nicht unmittelbar den Adapter unbrauchbar machen. Daher bitte ich dich um etwas Geduld ..

**Comment by RoboCop0815** [comment]
Kein Problem... gutes Gelingen bei der 2.xLG Robbie-- Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 11.12.21, 11:45 schrieb Xenon-s ***@***.***>:

   
  nein, gibt nichts neues 
  Ich bin bereits mit der neuen 2.0 angefangen und entwickle die 1.x nicht mehr weiter. Auch keine Bugfixes, die nicht unmittelbar den Adapter unbrauchbar machen. Daher bitte ich dich um etwas Geduld ..
