### ISSUE TITLE
Wiederholende Erinnerung

### ISSUE THREAD

**Issue by Trrw** [Xenon-s/ioBroker.device-reminder#133]
Wäre es möglich eine wiederholende Erinnerung einzurichten?

Beispiel: Die Waschmaschine ist fertig. Sollte die Tür nicht geöffnet werden (Türkontakt angebracht), kommt alle 20 Minuten erneut eine Nachricht, dass die Maschine fertig ist. Dies passiert 6 Mal. Danach kommt keine Meldung mehr.

So kann verhindert werden, dass die Wäsche in der Maschine vergessen wird.

Danke für deine Arbeit und dem tollen Adapter!

**Comment by Xenon-s** [comment]
steht bereits auf meiner Liste für die 2.0 ;)
