### ISSUE TITLE
Pushover custom sounds

### ISSUE THREAD

**Issue by Kev0123** [Xenon-s/ioBroker.device-reminder#143]
**!!! Before you start !!!!**  
Verify if there is not already an issue requesting the same Enhancement

**Describe wanted Enhancement !**  
A clear description of the wanted functionality

Pushover can use custom [sounds](https://blog.pushover.net/posts/2021/3/custom-sounds)

**Why should we put effort in it ?**  
Please add some additional information why this Enhancement should be integrated

The standard sounds are odd and wont allow a big differentiation between devices.

**Comment by Xenon-s** [comment]
Wo werden die sounds denn hochgeladen und wie kann man darauf dann zugreifen? Ich gebe nur den soundnamen an pushover weiter, den Rest macht der pushover adapter dann
