### ISSUE TITLE
Danke, jedoch...

### ISSUE THREAD

**Issue by HolgerOnGithub** [Xenon-s/ioBroker.device-reminder#15]
Hallo, gibt es eine Auflistung mit welchen Geräten die User diesen Adapter nutzen? Ich würde ihn gern nutzen, stehe jedoch vor dem Problem derzeit keine Information zu finden welche (als Beispiel ZigBee) Steckdosen die Messdaten liefern. Meine an der Fritzbox angeschlossene Fritz!DectSteckdose kann das jedoch kostet sie auch dementsprechend.
Danke im Voraus.

Gruss Holger

PS: die Leistung des angeschlossenen Verbrauchers spielt natürlich auch eine Rolle, jedoch stehen diese Daten ja bei den jeweilig auf dem Markt angebotenen Zwischensteckern dabei.

**Comment by Xenon-s** [comment]
Hallo Holger, du kannst diesen Adapter mit jeder Messsteckdose nutzen. Wichtig ist, dass die Daten regelmäßig reinkommen, bei tasmota oder Homematic kann man die intervalle auf 10 Sekunden und weniger einstellen.
Die Werte für den Verbraucher sind zweitrangig zu sehen, denn man kann die Schwellwerte ja im Adapter anpassen, sollten die default Werte nicht zu 100% passen

**Comment by HolgerOnGithub** [comment]
Vielen Dank für Deine schnelle Antwort. Punkt eins ich meinte das der Adapter natürlich für die Leistungsaufnahme des Gerätes geeignet sein soll :-D
Ansonsten war meine Frage tatsächlich auf die Produkte bezogen (welche genau) Da Du Tasmota geschieben hast wäre es z.B: der 11827 von DeLock. Ich hoffte das Du feedback Deiner Adapternutzer hast welche Geräte genau sie nutzen da ich noch vor der Anschaffung stehe und z.B. nun ein geeignetes Gerät als Zwischenstecker oder Zwischenbau für die Waschmaschienen, Geschirrspüler Stromversorgung suche um anschließend mit Deinem Adapter auszuwerten ob diese Geräte "fertig" sind. Das eigentliche Ein bzw. Ausschalten was diese Zwischenstecker etc. eigentlich machen ist natürlich quatsch. Ich hoffte das es daher Geräte gibt die ZigBee unterstützen da es natürlich zusätzliche Stromverbraucher sind (Strom ist natürlich kein Problem weil in der Steckdose natürlich immer vorhanden) aber auch die WLAN Belegung ist bei der Vielzahl an Geräten natürlich irgend wann zu berücksichtigen.

**Comment by Xenon-s** [comment]
Welches Gerät du nutzt ist dir überlassen. Ich selber nutze aktuell gosund sp111 mit tasmota, werde aber sobald erhältlich auf zigbee umsteigen. Soweit ich weiß, gibt's da auch schon Zwischenstecker. Du müsstest sonst im forum mal fragen, vielleicht bekommst du da Auskunft welche Geräte so im Einsatz sind. 

https://forum.iobroker.net/topic/37915/test-adapter-device-reminder-v0-x/361

**Comment by HolgerOnGithub** [comment]
Das werde ich tun. Vielen Dank.
