### ISSUE TITLE
consumption in kwh

### ISSUE THREAD

**Issue by tsfuchs** [Xenon-s/ioBroker.device-reminder#166]
Your iobroker module is very cool and I plan to retire my own scripts. But I miss one little thing:

My skript calculated the consumption in kwh since the start, saved it to a iobroker object and at the end it said sth like:
The dishwasher is finished :) 
It was consumed in 2:05h 1.633 kWh.

**Comment by Xenon-s** [comment]
Hi tsfuchs, I will look at it, but currently have a lot on my plate privately

**Comment by emanuelwo** [comment]
I added your feature request here: https://github.com/emanuelwo/ioBroker.device-reminder.git
if it works for you, i make a pull request.

From the readme:

> ## Placeholder in End Text
> 
> - total consumption: If the data point returns Wh, use the placeholder **{consumption in Wh}**, otherwise **{consumption}**. There is always a conversion to kWh
> 
> An example of the end text: 'The washing machine is ready. Consumption: {consumption in Wh} kWh'
> 
> - Runtime output: **{runtime}**
> 
> An example of the end text: 'The washing machine is ready. Running time: {runtime}'

**Comment by Xenon-s** [comment]
please put a PR and I'll take a look at it. Actually, however, in the future the adapter should recognize which unit is used and adjust the calculation independently
