### ISSUE TITLE
No telegram-option available

### ISSUE THREAD

**Issue by bh1rschk0rn** [Xenon-s/ioBroker.device-reminder#167]
After i installed the Adapter (Version 1.2.9) on my iobroker, i can define my devices. But i have noch possiblity to select an notification by telegram. I use telegram in different ways (by script or different adapters). I have two instances installed of telegram.

**To Reproduce**  
Open device-reminder to config the devices. Search the option for telegram.

**Expected behavior**  
As mentioned, i expect a visible configuration for telegram

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.2.9
 - JS-Controller version: 4.0.21
 - Node version: v12.16.2
 - Operating system: raspbian

**Additional context**  
<img width="1788" alt="2022-03-17 11_21_41-instances - iobroker" src="https://user-images.githubusercontent.com/101801063/158788875-313a4afd-3167-43ea-a6a3-1c4c7b7dd1bc.png">
<img width="577" alt="2022-03-17 11_24_22-instances - iobroker" src="https://user-images.githubusercontent.com/101801063/158789373-7445fcb2-2af4-4115-af29-7e3133991395.png">

**Comment by Xenon-s** [comment]
The whole thing can be, because there can be timing problems in the current adapter every now and then. I am since longer time in the process to build a completely new version. Usually it helps to reload the page several times (don't restart the instance, but refresh the browser)

**Comment by bh1rschk0rn** [comment]
Thanks for your reply. Unfortunately several times refreshing doesn't solve my problem. I also tried to use another browser like microsoft edge.
I really like this adapter. The handling is very easy.

If you need help (like beta tester) you can contact me. I'm a software developer, with main focus on java, but i can read and write javascript.

**Comment by Xenon-s** [comment]
Thanks for your offer. You are also welcome to further develop the adapter together with me 😉

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen

**Comment by Xenon-s** [comment]
2.1.2
