### ISSUE TITLE
New Pushover instance is ignored

### ISSUE THREAD

**Issue by eric2905** [Xenon-s/ioBroker.device-reminder#169]
Adding a new instance of Pushover, but this new instance is not recognised by the device-reminder.
It is not possible, to choose it from the pulldown menu.

Instance restart did not help

Adapterversion 1.2.9

**Comment by Xenon-s** [comment]
Hi Eric, I will look at it, but currently have a lot on my plate privately

**Comment by Xenon-s** [comment]
in the next version it should be fixed

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen

**Comment by Xenon-s** [comment]
2.1.1
