### ISSUE TITLE
[ERROR] {sendMsg: TELEGRAM}: "TypeError: Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by chrgachrga** [Xenon-s/ioBroker.device-reminder#170]
when adding a second receipient for telegram, the message goes through to the first recipient, but for the second recipient I get the following error message in the log:
[ERROR] {sendMsg: TELEGRAM}: "TypeError: Cannot read property 'name' of undefined"

**Expected behavior**  
Message goes through to both recipients

**Screenshots & Logfiles**  
[ERROR] {sendMsg: TELEGRAM}: "TypeError: Cannot read property 'name' of undefined"

**Versions:**  
 - Adapter version: 1.2.9 --------- Telegram is 1.11.1
 - JS-Controller version: 4.0.21
 - Node version: 12.22.10
 - Operating system: ubuntu

**Comment by Xenon-s** [comment]
This is not a bug, you have selected the wrong user. If you select firstname in the Telegram adapter, you must also select firstname in the device reminder. If you use the username, then you must select the username

By the way, the error always occurs when you select the wrong user as target.

**Comment by chrgachrga** [comment]
Hi, these are my users:

```
{
  "11111111111": {
    "firstName": "Chris"
  },
  "11111111112": {
    "firstName": "Maren"
  }
}

```

So Telegram adapter is configured in a way so it uses first name, not user name.
In device reminder I can only select these two names, so there are no other options to choose from. So I can not really see what I have done wrong.
Or are you saying it might be worth changing telegram to using user name?
For user Chris the messages are going through, for user Maren I get the above error message, even though they are configured the same way.

Not sure where I get lost here!?

**Comment by chrgachrga** [comment]
any thoughts on this one? Any further Info needed?

**Comment by Xenon-s** [comment]
Sorry viel um die Ohren

Du kannst den Adapter mal auf debug umstellen und schauen, an wen device-reminder dann wirklich sendet. Zum test eben einen Datenpunkt erstellen und Werte von hand eingeben (Werte müssen aber BESTÄTIGT eingegeben werden!)

Oder unter Objekte -> system -> Adapter (Expertenansicht) device-reminder -> Instanz rechts auf den Stift gehen, dann öffnet sich ein json. Da steht dann auch dein Telegram User drin (eventuell ist der leer, war mal ein Bug der eigentlich weg sein sollte)

![IMG_20220329_202744](https://user-images.githubusercontent.com/65488191/160680345-2abffe1b-dc6d-49db-afb4-8fa20a1026e9.jpg)

![IMG_20220329_202631](https://user-images.githubusercontent.com/65488191/160680159-ddd9a9e4-be24-4bd0-84d8-2e12ee652b94.jpg)

**Comment by Xenon-s** [comment]
2.1.1
