### ISSUE TITLE
Pushover Title selbst wählen

### ISSUE THREAD

**Issue by ciddi89** [Xenon-s/ioBroker.device-reminder#171]
Hallo,

wäre es möglich eine Funktion einzufügen das man den Title in Pushover selbst wählen könnte? Nutze zb. Title für verschiedene Arten von Benachrichtigung (Sicherheitssystem, Haushalt, ioBroker usw.).

Vielen Dank schon mal. :)

ciddi89

**Comment by ciddi89** [comment]
Alles gut kein Stress. Das geht mir gerade genau so. :)

**Comment by Xenon-s** [comment]
wird das einfach als String übergeben?

**Comment by ciddi89** [comment]
Ja genau. Hier ein Beispiel aus einem Adapter von mir:

```
await this.sendToAsync(this.config.instancePushover, 'send', {
	message: text,
	title: this.config.titlePushover,
	device: this.config.devicePushover,
	user: this.config.userPushover,
	priority: this.config.prioPushover,
});
```

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen

**Comment by Xenon-s** [comment]
2.1.1
