### ISSUE TITLE
IoB dark Theme and device-reminder font colour

### ISSUE THREAD

**Issue by kuckuckmann** [Xenon-s/ioBroker.device-reminder#172]
Hi,

it's not really an issue but it's uncomfortable. 
Based that an opened edit part (pulldown area) is having a white background-colour and IoB font-colour is also white while using IoB dark Theme, it's hard to read the stuff.

Thx
Kuckuck

**Comment by Xenon-s** [comment]
next update:

![image](https://user-images.githubusercontent.com/65488191/168078980-ba4d44f3-becb-4fe1-a14b-d96f8dc44c60.png)

![image](https://user-images.githubusercontent.com/65488191/168079030-69593b86-da13-4e72-b39e-37e86f315e22.png)
