### ISSUE TITLE
Zähler für Gerät in Aktion

### ISSUE THREAD

**Issue by BenAhrdt** [Xenon-s/ioBroker.device-reminder#173]
Es wäre ein schöner Indikator, wenn es einen Zähler für die Aktivierung geben würde.
Bspw. ganz simple wenn ein Gerät aktiviert wird den Zähler hoch zählen.

**Comment by Xenon-s** [comment]
Wie genau meinst du das? Ich verstehe dich nicht so recht...

**Comment by BenAhrdt** [comment]
Na einfach einen counter, wenn ein Gerät vom Zustand aus / standby in den Zustand aktiv wechselt.
=)> dann den counter eins hoch zählen.

**Comment by Xenon-s** [comment]
ich hab mich mal wieder ran gesetzt. Ich denke, dass das ganze machbar sein sollte ;)

**Comment by Xenon-s** [comment]
https://github.com/Xenon-s/ioBroker.device-reminder/issues/181
