### ISSUE TITLE
Verbrauch und Zähler

### ISSUE THREAD

**Issue by RitterP** [Xenon-s/ioBroker.device-reminder#181]
Wäre es möglich, einen Zähler hinzuzufügen (z.B. die Waschmaschine ist bisher schon X mal gelaufen)?

Auch wäre eine Überwachung des Stromverbrauches schön, (z.B. letzter Vorgang 1,75 kWh)

**Comment by Xenon-s** [comment]
> Wäre es möglich, einen Zähler hinzuzufügen (z.B. die Waschmaschine ist bisher schon X mal gelaufen)?
Sollte problemlos einbindbar sein
> Auch wäre eine Überwachung des Stromverbrauches schön, (z.B. letzter Vorgang 1,75 kWh)
Wo soll ich die Daten herbekommen? Ich arbeite nur mit dem Liveverbrauch in W. Daten in kWh liegen mir nicht vor und sind somit auch nicht abrufbar für den Adapter

**Comment by Xenon-s** [comment]
Ich hab mir das Ganze nochmal angeschaut. Ich werde es nicht integrieren. Das Problem was auf mich nämlich zu kommen wird ist folgendes:

Es gibt immer mal falsche Erkennungen, vorallem bei den neuen Geschirrspülern. Dann werden wieder issues kommen, weil der Zähler nicht passt.

Es sollte aber problemlos für jeden machbar sein, sich einen Datenpunkt anzulegen und diesen jedes Mal +1 zu zählen wenn ein Gerät zb den Status "In Betrieb" hat. Wenn es da Probleme gibt, helfe ich gerne weiter.
Das json, welches die letzten Durchgänge anzeigt, ist auch limitiert worden, aus den oben genannten Gründen.

Trotzdem danke für deinen Vorschlag
