### ISSUE TITLE
Gleichzeitige Nachricht an mehrer WhatsApp-User

### ISSUE THREAD

**Issue by Clasenf** [Xenon-s/ioBroker.device-reminder#182]
Hallo,

ich habe zwei WhatsApp-Empfänger eingetragen! Es bekommt aber immer nur der als erstes eingetragene Empfänger die Nachrichten, obwohl beide angehakt sind. 
Ist das so richtig oder verstehe ich die Auswahlmöglichkeit falsch?

**Comment by Xenon-s** [comment]
Hallo, nein das ist so nicht richtig. Kannst du mal deine Objekt Ansicht auf Experte stellen und dann unter "System - device-reminder" mit einen Auszug zeigen, von dem WhatsApp Teil?

Hier findest du den Weg dorthin... Namen dürfen gerne gegen alias ersetzt werden

**Comment by AndreasL384** [comment]
Hallo,
ich habe das gleiche Problem.
Hier mal mein Auszug aus den Objektdaten:
`{
  "_id": "system.adapter.device-reminder.0",
  "type": "instance",
  "common": {
    "name": "device-reminder",
    "version": "1.2.9",
 ...
    "installedFrom": "iobroker.device-reminder@1.2.9",
    "installedVersion": "1.2.9",
    "host": "FELISRV",
    "logLevel": "info"
  }
,..

    "whatsapp": {
      "id": [
        {
          "name": "[0]cmb",
          "nameFinal": "[0]cmb",
          "id": 0,
          "inst": ".0"
        }
      ],
      "final": {
        "0": {
          "name": "[0]cmb",
          "path": "whatsapp-cmb.0.sendMessage"
        }
      }
    },
 `

Ich hoffe das passt so. Ich sehe nur den Eintrag für WhatsApp[0], der ja auch funktioniert.
