### ISSUE TITLE
Aktualisierungsrate

### ISSUE THREAD

**Issue by BenAhrdt** [Xenon-s/ioBroker.device-reminder#183]
Wie oft aktualisiert der Adapter denn die Leistungen?
Alle 5s?
Denn sie werden nicht bei Änderung aktualisiert, oder?

**Comment by Xenon-s** [comment]
Der Adapter speichert sich jede Änderung eines Wertes und nutzt ihn dann so lange, bis er sich wider ändert.
Mit diesem bekannten Wert wird dann alle 10 Sekunden gerechnet und das Ergebnis in den Datenpunkt "average consumption" geschrieben. Dieser Wert wird mit deinen Schwellwerten abgeglichen

**Comment by BenAhrdt** [comment]
ah ok, also wenn man 2 mal angibt, sind es quasi 20s, welche unterhalb / oberhalb des schwellwerts liegen müssen?
Oder 20s der durchschnittswert?

**Comment by Xenon-s** [comment]
Nein, die Berechnung ist etwas komplexer. Steht aber eigentlich ganz gut beschrieben in der Doku zum Adapter. Lies dir die mal durch und wenn noch Fragen sind einfach hier wieder melden 🙂

**Comment by BenAhrdt** [comment]
ok, danke., gehe aber mal davon aus, wenn ich 0W habe und sich das nicht mehr ändert, dann würde es passen, wenn Du sagst alle 10s Mittelwert und dann x 2.
