### ISSUE TITLE
pushover device-name Feld in pushover user

### ISSUE THREAD

**Issue by Keven6077** [Xenon-s/ioBroker.device-reminder#185]
Um nur an bestimmte pushover devices zu senden und nicht an alle Geräte der Instanz, bräuchte man zusätzlich den `device name`, welche bei pushover registiert ist.

![pushoverDeviceNameGeräteID](https://user-images.githubusercontent.com/59521882/163792408-181b77fa-472f-4529-b5b5-ecfb94abfa9a.png)

[https://pushover.net/](url)
![pushoverDeviceName](https://user-images.githubusercontent.com/59521882/163790751-9f124e00-1399-4a81-8150-3df0b3b62ad4.png)

In Blockly ist das durch die `Geräte ID (optional)` realisiert.
![pushoverDeviceNameBlockly](https://user-images.githubusercontent.com/59521882/163790977-ac1e9734-d70c-4e1f-88b6-70bdf28daf65.png)

In der JSON wäre dafür das key:value `device: 'device-name'` nötig.
```json
{
   message: 'text',
   sound: "pushover",
   device: 'device-name'
}
```

**Comment by Xenon-s** [comment]
schau ich mir an, aber wie auch bereits bei den anderen issues bereits geschrieben: es wird dauern, aktuell wirklich keine Zeit die neue Version weiter zu entwickeln

**Comment by Xenon-s** [comment]
kurzes Update dazu:

Eventuell bereits im nächsten Update enthalten

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen
