### ISSUE TITLE
Sonos & Alexa

### ISSUE THREAD

**Issue by skapi85** [Xenon-s/ioBroker.device-reminder#194]
Hallo,
folgendes ist mir bei meinem Sonos System in Kombination mit Alexa aufgefallen:
 - Das Announcement wird nicht bei allen Lautsprechern ausgegeben (alle ausgewählt - einzeln funktionieren die Ankündigungen)
 - Die ursprüngliche Lautstärke wird nach dem announcement nicht wieder hergestellt (d.h. die Wiedergabe nach der Ankündigung wird z.b. mit Vol. 50 fortgesetzt was dann schon ziemlich laut sein kann)

**Comment by Xenon-s** [comment]
Hallo, was genau soll ich mit so wenig Infos anfangen? Was genau ist jetzt das Problem? 
Das nicht immer alle alexas melden kenne ich von meinen eigenen. Liegt aber nicht am Adapter sondern am alexa Adapter oder den Amazon Servern

**Comment by TripleX1978** [comment]
@skapi85 Das die Meldungen nicht bei allen Geräten ausgegeben wird hatte ich auch.
Ich hab es für die Alexa-Geräte so gelöst, dass ich in der Alexa-App eine Gruppe erstellt habe.
Diese kann  man in dem Adapter auch ansprechen und es funktioniert bei mir bisher ohne Probleme.
Die Probleme mit der Lautstärke habe ich nicht.
Nach der Meldung geht es mit der ursprünglichen Lautstärke weiter.

**Comment by skapi85** [comment]
Ich hab mich damit nicht mehr weiter beschäftigt….  Ich hab’s mit dem sayit Adapter gelöst und das funktioniert wunderbar ☺️ 
Danke @TripleX1978 for den Hinweis!
