### ISSUE TITLE
Telegram-User nicht immer sichtbar, Abschalten geht nicht mit "0"

### ISSUE THREAD

**Issue by guergen1** [Xenon-s/ioBroker.device-reminder#2]
Technisch scheint er zu laufen (s.u.) , allerdings wird der Telegram-User nicht angezeigt beim erneuten aufruf des Adapters (korrektur: nicht immer, aber jedes 2. Mal)
e6148165-d78a-45ba-bba9-4c61a11d040a-grafik.png
![grafik](https://user-images.githubusercontent.com/34395245/97026431-a6d23a00-1559-11eb-99c3-576ce9a1d137.png)

Bei meinem Wasserkocher einen Timeout von 0 Minuten eingetragen, aber wird nicht abgeschaltet!

Beim Eintrag von 1 Minute geht es!

**Comment by guergen1** [comment]
Da der Telegram-User nicht immer sichtbar ist, weiss man nicht, ob er aktiv oder nicht ist. Daher kann man ihn, wenn er einmal aktiviert wurde, auch nicht deaktivieren!
Auch wenn er scheinbat deaktiviert ist, werden Nachrichten versendet!
![grafik](https://user-images.githubusercontent.com/34395245/97111095-2d635480-16dd-11eb-937a-3eb2499fced2.png)

**Comment by Xenon-s** [comment]
beide Fehler sind im nächsten update auf 0.3 behoben
