### ISSUE TITLE
active => switched off

### ISSUE THREAD

**Issue by MotschaM** [Xenon-s/ioBroker.device-reminder#202]
Super Adapter, aber leider nervt mich die ständige Benachrichtigung auf Telegram: "active => switched off" oder "active => switched on" möchte diese Nachricht nicht mehr erhalten, ob der Schalter on oder off ist. Was muss ich wo einstellen, damit diese Benachrichtigung nicht mehr kommt? Die eigentliche Telegram Meldung, dass die Maschine fertig ist, soll weiterhin statt finden. 

Danke

**Comment by Xenon-s** [comment]
du bekommst nur die meldungen, dass fertig oder gestartet ist, wenn du was in die Felder einträgst. Der Adapter meldet nicht, wenn der Switch umgeschaltet wird .. oder was meinst du?
