### ISSUE TITLE
start/end-benachrichtigung optional einstellbar

### ISSUE THREAD

**Issue by zokkai** [Xenon-s/ioBroker.device-reminder#203]
Super Adapter. Mir erspart er sehr viel Blockly-arbeit :-)

Ich habe keinen Weg gefunden, Nachrichten einzeln zu steuern. 
Gerade das Senden von Startnachrichten ist IMHO nicht immer nötig.
Es wäre daher sinnvoll, die Start/End-Nachrichten wahlweise ein/auszuschalten.

Danke!

**Comment by Xenon-s** [comment]
solange du das Feld leer lässt, kommt keine Nachricht. Oder was meinst du?

**Comment by zokkai** [comment]
Ahh, war es doch so einfach. Ich habe dies gar nicht getestet.
Ich dachte, wenn der Adapter aktiviert ist, sendet er in jedem Fall die Nachrichten, unabhängig davon, ob im Benachrichtigungs-Textfeld etwas steht oder nicht.

Vllt. ist eine kurze Erwähnung in der Beschreibung hilfreich für Andere.

Danke!
