### ISSUE TITLE
Berechnung der Anzahl der Endwerte

### ISSUE THREAD

**Issue by BertiSto** [Xenon-s/ioBroker.device-reminder#208]
Hallo Xenon-s,

kann es sein, dass die Berechnung der "Anzahl Endwerte" bei z.B. "dishwasher" sich auf "live consumption" und nicht "average consumption" bezieht?

Danke und Grüße

**Comment by Xenon-s** [comment]
Dann würde der Adapter nicht funktionieren. Der live Verbrauch wird nur beim Start berücksichtigt, ab dann wird der Durchschnitt genommen
