### ISSUE TITLE
Alexa und Device-Reminder bringt Error 

### ISSUE THREAD

**Issue by helfi9999** [Xenon-s/ioBroker.device-reminder#209]
Hallo,
bekomme folgende Meldung sobald die Waschmaschine läuft, was sich auch auf den Alexa Adapter auswirkt:
![Device](https://user-images.githubusercontent.com/43864283/180287418-a163d824-a3d7-46f9-88bb-9139dacac148.png)

**Versions:**  
 - Adapter version: <1.2.9>
 - JS-Controller version: <4.0.23> 
 - Node version: <16.16.0> 
 - Operating system: <debian>

Vielleicht jemand hier der das gleiche Problem hat

**Comment by spoeh-man** [comment]
Ja bei mir das gleiche

**Comment by Xenon-s** [comment]
https://github.com/Xenon-s/ioBroker.device-reminder/issues/207

**Comment by ali86x** [comment]
Bei mir leider auch das gleiche.

**Comment by Xenon-s** [comment]
Ich habs oben doch schon extra geschrieben: 
https://github.com/Xenon-s/ioBroker.device-reminder/issues/207
Hintergrund:
Ich habe derzeit und auch auf absehbare Zeit keine Zeit mehr für eine Weiterentwicklung, daher bitte die aktuelle Version von github installieren, da ist der Fehler weg.
