### ISSUE TITLE
Whatsapp Report an mehrere Empfänger nicht möglich

### ISSUE THREAD

**Issue by jolu1705** [Xenon-s/ioBroker.device-reminder#210]
**Describe the bug**  
Ich habe bei der Notification 2 Empfänger für Whatsapp eingetragen ([0]cmb, [1]cmb)
Der erste [0]cmb erhält Nachrichten. Der zweite Empfänger nicht.

**To Reproduce**  
...mehrere Whatsapp Empfänger eintragen

**Expected behavior**  
Alle eingetragenen Empfänger sollen die Nachrichten erhalten

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.2.9
 - JS-Controller version: 4.0.23
 - Node version: 14.17.3
 - Operating system: Linux optiplex7050 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64         GNU/Linux

**Comment by Joern66** [comment]
Hallo, ich habe das gleiche Problem mit telegram.
Einen zweiten User eingetragen, der aber keine Meldungen erhält.

Im Protokoll steht dazu die Meldung:
[ERROR] {sendMsg: TELEGRAM}: "TypeError: Cannot read properties of undefined (reading 'name')"

**Comment by Xenon-s** [comment]
> Im Protokoll steht dazu die Meldung: [ERROR] {sendMsg: TELEGRAM}: "TypeError: Cannot read properties of undefined (reading 'name')"

dann hast du, wie zahlreiche andere User auch immer wieder, im telegram Adapter einen falschen Haken gesetzt (zB: Firstname aktiv, sendest aber an Username). Da kann der Adapter aber nichts für, dass ist eine Telegram Sache ;)

**Comment by Xenon-s** [comment]
> **Describe the bug** Ich habe bei der Notification 2 Empfänger für Whatsapp eingetragen ([0]cmb, [1]cmb) Der erste [0]cmb erhält Nachrichten. Der zweite Empfänger nicht.

Da ich selber kein Whatsapp nutze, kann ich es nicht testen. Bei whatsapp wird direkt in den ausgewählten Datenpunkt geschrieben. Und im Datenpunkt von cmd1 steht dann nichts? Nur in cmd0?

**Comment by jolu1705** [comment]
[ERROR] {sendMsg: WHATSAPP}: "TypeError: Cannot read properties of undefined (reading 'path')" tritt immer noch auf. 
Der Adapter mag wohl mehrere Whatsapp Instanzen nicht.

Wie kann ich Dir helfen das Problem zu identifizieren und zu beheben?

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen

**Comment by Xenon-s** [comment]
V 2.1.2
