### ISSUE TITLE
Erweiterungen

### ISSUE THREAD

**Issue by DerSlimmy** [Xenon-s/ioBroker.device-reminder#213]
Hi, 
erst mal danke für den Adapter. Habe ihn gerade installiert und werde ein bisschen testen.
Ich habe bisher was selbst gestriktes. Mir wäre es aber lieber über diesen Adapter.
Wären folgende optionale Erweiterungen möglich bzw würdest du die einbauen?
- Statt speak ssml auswählen. Dann kann man die Stimmer usw personalisieren in dem man bestimmte strings übergibt
- Statt alexa speak eine Benachrichtigung machen. Wenn ich weg bin und kein Pushover usw nutze, dann sehe ich den gelben Ring wenn ich heim komme und kann Alexa fragen was ist. Und dann kommt der definierte Text ja

Wie gesagt beides als weitere optionen

Gruß Oli

**Comment by Xenon-s** [comment]
> * Statt speak ssml auswählen. Dann kann man die Stimmer usw personalisieren in dem man bestimmte strings übergibt

Ich nutze Alexa nicht. Was genau muss denn da übergeben werden?

> * Statt alexa speak eine Benachrichtigung machen. Wenn ich weg bin und kein Pushover usw nutze, dann sehe ich den gelben Ring wenn ich heim komme und kann Alexa fragen was ist. Und dann kommt der definierte Text ja

Wie wird denn eine Benachrichtigung bei Alexa über ioBroker erstellt? Ich sende einfach per sendTo() an den Alexa Adapter, der macht dann den Rest
