### ISSUE TITLE
Ansage nach Uhrzeit auswählbar

### ISSUE THREAD

**Issue by JBSullivan** [Xenon-s/ioBroker.device-reminder#23]
Mit meiner Frau ist gerade eine Diskussion entbrannt bzgl. der Sprachansage. Konkret geht u.a. um die Waschmaschine. Sie hätte gerne die Möglichkeit, das man eine Uhrzeit einstellen kann, wann die Sprachansage (nochmal) ausgegeben werden soll (z.B. als letzte Erinnerung des Tages wenn man am Abendbrot Tisch sitzt (18:30 Uhr o.ä.). 

Ihre Begründung, wenn Sie nicht zu Hause ist und die Ansage kommt, dann hört Sie es nicht und vergisst es dann doch wieder das die Maschine fertig ist.
Die Sprachansage kommt ja dann, wenn die eingestellten Lastparameter erreicht sind. Man kann zwar das TimeOut einstellen, aber das bezieht sich ja auf die Abschaltung.
Hier geht es auch nicht ums abschalten der Maschine, das will sie gar nicht (wegen Knitterschutz) Sie will einfach zu einer bestimmten Zeit daran erinnert werden, das noch was in der Maschine drin ist. 

Des weiteren will sie, das nur bestimmte Sprachansagen nur auf bestimmten Alexas ausgegeben werden.

Beispiel: Waschmaschine und Wäschetrockner sollen nur in der Küche, Stube und Schlafzimmer ausgegeben werden. Der Geschirrspüler ist ihr aber egal und da will sie KEINE Ansage im Schlafzimmer, sondern nur auf den Toiletten und im Bastelkeller haben. Schlafzimmer muss aber verknüpft sein, weil es sonst die Ansagen für Waschmaschine & Wäschetrockner nicht gäbe. Geschirrspüler muss ebenfalls definiert sein, weil sonst die anderen Räume nicht erreicht würden.

Also eine Zwickmühle bzgl. ihrer Vorstellungen ;)

**Comment by Xenon-s** [comment]
hallo, ich bin derzeit am überlegen einen Anwesenheits Datenpunkt lesend zu integrieren. Dh der User kann einen Datenpunkt angeben, welcher dem Adapter mitteilt, ob jemand anwesend ist

**Comment by JBSullivan** [comment]
Würde in meinem Fall nichts bringen, da ich nur auf ein Handy als Anwesenheit Triggern könnte und das vergisst meine Frau regelmäßig, bzw. nimmt es nicht mit, wenn sie z.B. im Garten am buddeln ist. Dann kommt im Haus die Ansage und draußen hört sie es nicht.
Auch wenn ich es ungern zugebe, so eine "Tagesabschluss Meldung" wäre schon was ;)

**Comment by Xenon-s** [comment]
.. sowas ist zu individuell, man hat schließlich auch immer noch die Möglichkeit selber auf Datenpunkte zu reagieren oder sich per Messenger informieren zu lassen
