### ISSUE TITLE
Add functionality for change based power monitor devices which do not support cyclic value updates

### ISSUE THREAD

**Issue by benzolo** [Xenon-s/ioBroker.device-reminder#231]
Currently device-reminder only supports power monitoring devices which report the current power consumtion of the monitored device in a cyclic maner. E.g. every 10 seconds. This is not the case for all power consumtion monitor systems. E.g. some KNX based power monitor systems like this one included in the actuator from MDT 
https://www.mdt.de/en/products/product-detail/actuators/switch-actuators/switch-actuators-ams-with-current-measurement.html
only allows you to configure different thresholds when a new value is sent. E.g. a value change in 1%,2%, 5%,.. will triger a new data event depending on the configuration. It is possible to a add cyclic reportings but with 15 minutes as smallest cycle time, to reduce bus load on the KNX bus. Therefore relying on cyclic transmission of the power consumption does not work for this kind of devices. 
In my case I tried to monitor a washing machine with a MDT AWS 1216 actuator with built in current / power measurement. The detection did work with the default config but the events for started and ended of the program where delayes quite a bit. Critical would be tjhe detection fof the program end as it was delayed by arround 15 minutes in my case. I think the adapter run in some kind of maximum timing after the washing machine went to its standby currend and remaind there with no new power status updates from the power mesurement system in the actuator.
For such devices to work some timing related configuration, rather then number of cycles with new measurements would be needed to define the time elapsed after the threshold for on / off has been passed

**Comment by Xenon-s** [comment]
The adapter puts triggers on the live consumption data point. If this value changes, it is built directly into the next calculation. If the value does not change for 15 minutes, the old value is used for 15 minutes. 
How exactly I should change something there is a mystery to me
