### ISSUE TITLE
Adapter schickt keine Endtexte!!

### ISSUE THREAD

**Issue by Bullet586** [Xenon-s/ioBroker.device-reminder#239]
Hi,

ich hab ne Frage und hab ein Problemchen. Bei mir schickt der Adapter keine Endtexte wenn die Geräte fertig sind. Zudem sind die variablen "Last Runtime" + "Last Operations" Konstant leer, vollkommen egal wie oft ich die Geräte laufen lasse. Hast du ne Idee wo das Problem liegen könnte? Oder irgendjemand? Ich flipp echt bald aus, find einfach das problem nicht.

Ich hab keine Standardwerte verändert! Nachrichten verschicken und Sprachausgabe über Alexa funktioniert ebenfalls einwandfrei, aber wie gesagt nur mit den Starttexten.

Thanks a lot

**Comment by Bullet586** [comment]
zur Ergänzung
![Screenshot 2022-12-09 173849](https://user-images.githubusercontent.com/120199755/206749664-db3cdcb6-f91a-4c0b-9512-34941f90c10d.jpg)
 (siehe Bild)

**Comment by Bullet586** [comment]
Nachtrag zu dem Thema. Variablen werden mittlerweile alle befüllt. Die Status variablen auch korrekt getriggert, somit geht wie gesagt nur das Feedback nach Beendigung nicht, weder Nachrichten noch Sprachausgabe. Hab mir zwar mittlerweile ein blockly geschrieben was das nun übernimmt, soll ja aber nicht Sinn und Zweck des Adapters sein.

**Comment by Bullet586** [comment]
Ja bei allen Geräten Ist Abbruch Erkennung aktiv, ich werd es mal morgen rausnehmen und Testen wie es sich dann verhält.

**Comment by ciddi89** [comment]
Ja mach mal, habe auch wie blöd gesucht bis ich die checkbox gefunden habe und den Haken rausgenommen habe 😂 seit dem funktioniert das bei drei Geräten jedes Mal 👍🏻

**Comment by Xenon-s** [comment]
Bitte issue nicht schließen, das schau ich mir an. Wenn ich denn mal wieder Zeit habe, was vorerst nicht der Fall ist

**Comment by Bullet586** [comment]
Hatte heute mal Zeit dafür, Abbruch Erkennung raus nehmen hat nichts gebracht, kommen immernoch keine Meldung. Weder Sprachausgabe noch pushover, außer vom Script was ich geschrieben habe. Wenn es gehen würde müsste ich 2 mal den gleichen Text bekommen, geht aber wie gesagt nicht. Aber wie gesagt momentan Stör es mich nicht mehr, mein Script ersetzt das Problem.

**Comment by Bullet586** [comment]
Hast du was gemacht an dem Problemchen?

**Comment by Xenon-s** [comment]
Es liegt eine neue Version 2.0.1 auf npm. Die hat sehr viele Dinge behoben 😉 sollte doch wieder was sein, melden 😉
