### ISSUE TITLE
Feature Idea: Calculate price for power consumed

### ISSUE THREAD

**Issue by jardleex** [Xenon-s/ioBroker.device-reminder#24]
Hi,

As there is nothing in this direction I'd like to request an feature.

In the end of an machine run, let the user know how much money this run cost him. As a base requirement the device measuring the current power consumption also has to provide a data point about the total consumtion. This is the baseline of calculation for the end price.
In order to calculate the user has to provide the cost per kW in a input field or refer to an existing data point in iobroker. 

I'm aware of the feature to create custom start end end messages via data points. The enhancement nonetheless would allow the user to replace even more Blockly/Node-Red scripts.

Thanks and best regards

jard

PS: Fragen gern auch in Deutsch. Verfasste nur für die internationalen Benutzer in Englisch.

**Comment by Xenon-s** [comment]
Hello, no, I will definitely not integrate that. Incidentally, this request has already come up several times. That is also not the basic idea behind this adapter.
