### ISSUE TITLE
Integration für Matrix-Push

### ISSUE THREAD

**Issue by fir3drag0n** [Xenon-s/ioBroker.device-reminder#245]
Guten Tag,

schön wäre neben dem Push für Telegram usw. auch eine Integration für das offene Protokoll https://matrix.org/faq/
Einen iobroker Adapter gibt es dafür bereits schon: https://github.com/oelison/ioBroker.matrix-org

Dann kann man hier auch auf den Umweg über externe Dienste verzichten, da sich matrix auch wie iobroker komplett hosten lässt.

Beste Grüße und ein frohes neues Jahr!

**Comment by Xenon-s** [comment]
Ausversehen geschlossen

Ich schaue es mir an, sollte ich mal wieder Zeit haben

**Comment by Xenon-s** [comment]
kurzes Update dazu:
Ich versuche es im nächsten Update bereits einzubauen

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen
