### ISSUE TITLE
Telegram Message to Telegram instance

### ISSUE THREAD

**Issue by Maschine20** [Xenon-s/ioBroker.device-reminder#246]
Hello, 

Is it possible to send the notification to a Telegram instance in a future Version? So i will be independent for changes in the users in the Telegram-Adapter. 

Best regards
Maschine20

**Comment by Gittimmhub** [comment]
Since  v1.2.9  I wondering, why I don´t get any messages via telegram that my dryer is finish.

Please bring back these option.
Or someone can tell me witch was the last stable version with this support in?
Thanks

**Comment by Xenon-s** [comment]
The 1.2.9 is more than a year stable

**Comment by Gittimmhub** [comment]
> Die 1.2.9 ist mehr als ein Jahr stabil

ok, but how is it possible that i still received messages via telegram up until about a week ago and that there were also the telegram settings?
