### ISSUE TITLE
Fehlende Benachrichtigung von Telegram bei Verwendung des "Benutzer"

### ISSUE THREAD

**Issue by Duffy987** [Xenon-s/ioBroker.device-reminder#249]
**Nach der Aktivierung von "Benutzername anstatt Vorname von Benutzern speichern" in Telegram erhält man keine Nachrichten mehr aus device reminder**  

**To Reproduce**  
1. Go to 'In Telegram "Benutzername anstatt Vorname von Benutzern speichern" anhaken.'
2. Click on ''

**Expected behavior**  
Ich würde nun eine Meldung erwarten wenn ein Gerät startet oder beendet wird; überwacht durch device reminder

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <1.2.9>
 - JS-Controller version: <4.0.24> 
 - Node version: <v18.7.2> 
 - Operating system: <Ubuntu 20.10>

**Additional context**  
Hat man"Benutzername anstatt Vorname von Benutzern speichern" nicht angehackt wird
ausserdem, wenn man in Telegram einen Benutzernamen anlegt hat und diesen im device reminder auswählt (nicht Vor.- und Zunahme) im iobroker eine Fehlermeldung ausgegeben. Siehe unten.

<html><body>

device-reminder.0 | 2023-02-19 12:47:40.426 | error | [ERROR] {sendMsg: TELEGRAM}: "TypeError: Cannot read properties of undefined (reading 'name')"
-- | -- | -- | --

</body>
</html>

Einstellung verusacht Fehlermeldung
![Einstellung verusacht Fehlermeldung,](https://user-images.githubusercontent.com/120317770/219948073-1d560835-daac-4707-a2d2-0389ed4d4d76.jpg)
Einstellung verusacht keine Fehlermeldung
![Einstellung verusacht keine Fehlermeldung,](https://user-images.githubusercontent.com/120317770/219948084-bae56cf2-b3e8-428d-8df3-c12ab8572ee4.jpg)

**Comment by Xenon-s** [comment]
wieso sollte das ein Bug sein? Man muss schon den richtigen User auswählen, dass ist hier nicht anders wie auch bei jedem Blockly oder Javascript ;)
Und das der telegram Adapter nur entweder an den Username oder Firstname senden kann und nicht an beide, da kann ich nichts dran ändern ;)
