### ISSUE TITLE
Integration für CallMeBot (Signal Messenger)

### ISSUE THREAD

**Issue by firebowl** [Xenon-s/ioBroker.device-reminder#258]
Wäre cool wenn Du auch CallMeBot als Messenger einbauen könntest.
Gibt auch einen ioBroker Adapter für: [signal-cmb](https://github.com/derAlff/ioBroker.signal-cmb)

**Comment by Xenon-s** [comment]
schaue ich mir an ;)

**Comment by Xenon-s** [comment]
kurzes Update dazu:
Ich versuche es im nächsten Update bereits einzubauen. Allerdings benötige ich Daten dazu:

Wird per SendTo() an den Adapter gesendet wie bei zb Telegram oder geht das über Datenpunkte wie bei whatsapp? Gibt es wichtige Parameter, die zu konfigurieren sind?

**Comment by Cynric10** [comment]
Ich habe mir jetzt die 2.0.1 installiert und sehe den CallMeBot bzw. WhatsApp nicht, ist das noch im dev?

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen

**Comment by Cynric10** [comment]
Nice! Sieht gut aus die neue Version! 
Danke nochmal!
