### ISSUE TITLE
Fehlermeldung nach Update auf den neuen js-controller 3.2.x

### ISSUE THREAD

**Issue by Pocky2507** [Xenon-s/ioBroker.device-reminder#26]
device-reminder.0 | 2021-01-11 09:44:15.857 | warn (25105) State "device-reminder.0.Waschmaschine.config.auto Off" has no existing object, this might lead to an error in future versions
--

**Comment by Xenon-s** [comment]
Please send a screenshot of your objects. The data point "device-reminder.0.xxx.config.auto Off" does not exist


![objects](https://user-images.githubusercontent.com/65488191/104357019-f0a13f80-550c-11eb-8971-995235d9dbb0.jpg)

**Comment by Xenon-s** [comment]
will be fixed in next patch, thx
