### ISSUE TITLE
Adapter no longer starts under js-controller 5.0.5

### ISSUE THREAD

**Issue by AHahne64** [Xenon-s/ioBroker.device-reminder#267]
After an update to a new js-controller version the adapter does not start anymore. It is still a beta version. But it would be nice if the adapter later also work under the new versions again.

So far, the adapter has always worked without problems. 
Good work from the developers.

**Comment by Xenon-s** [comment]
F10 -> Developer options -> Console 
Do errors appear there?

**Comment by Xenon-s** [comment]
https://github.com/Xenon-s/ioBroker.device-reminder/issues/273
