### ISSUE TITLE
Adapter isn't any longer configurable

### ISSUE THREAD

**Issue by kuckuckmann** [Xenon-s/ioBroker.device-reminder#273]
**Describe the bug**  
The adapter isn't showing any configurations snaymore (no table) and it#s not possible to add or delete sth.

**To Reproduce**  
Open adapter

**Expected behavior**  
Configurations should beshown and it should beposiible to add/remove configurations

**Screenshots & Logfiles**  
![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/99131208/133c8902-e708-4bac-9ebd-aa53adb0b6b8)

**Versions:**  
 - Adapter version: 1.2.9
 - JS-Controller version: 5.0.5
 - Node version: 18.5.0
 - Operating system: Linux Debian 11

**Additional context**  
It's indepent of dark/light mode

**Comment by Xenon-s** [comment]
F10 -> Developer options -> Console
Do errors appear there?

**Comment by kuckuckmann** [comment]
Sth. like this:
![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/99131208/c2a54868-b3bf-4ea7-be97-cd35e96732ce)

**Comment by Menne01** [comment]
Das selbe bei mir:
![grafik](https://github.com/Xenon-s/ioBroker.device-reminder/assets/89869516/f11ae6ee-a164-4ea2-979e-08ae7a9eeb5c)

**Comment by crusader85** [comment]
Hier auch das Problem, neueste JS-Controller - Version drauf.

**Comment by Xenon-s** [comment]
Ich habe die komplette GUI neu geschrieben, allerdings hakt es hier und da noch ein wenig. Der aktuelle Entwicklungsstand kann unter "https://github.com/Xenon-s/ioBroker.device-reminder/tree/2.xDEV-VERSION" verfolgt werden. Nur niemals in Produktivsystem installieren!

**Comment by Xenon-s** [comment]
![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/65488191/99655f39-fb8b-4031-8f7a-8395dd4dd1e3)
![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/65488191/effe12f8-f4a2-4bff-b14e-b147ae9926ba)

Etwas Zeit brauche ich aber noch, da einiges noch fehlt ..

**Comment by Xenon-s** [comment]
bitte per Katze installieren und testen:

https://github.com/Xenon-s/ioBroker.device-reminder

**Comment by allesclip** [comment]
Hallo,

bei mir erscheinen nach der Installation keine Gerätetypen bei der Einrichtung.

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/47133057/bcb8a823-8384-4e13-9fc2-2b903e74434e)

**Comment by Xenon-s** [comment]
@allesclip nach der Installation von github?

**Comment by allesclip** [comment]
Ja genau. Ist die Version noch 1.2.9?

**Comment by Xenon-s** [comment]
Ja, die ziehe ich erst hoch wenns funktioniert. Bin schon am Suchen

**Comment by kuckuckmann** [comment]
Sieht mit der Version in etwa wieder so aus wie vorher.
Allerdings ist das Hell/Dunkel problem immernoch existend...nur ein kleiner Hinweis ;-)

**Comment by Xenon-s** [comment]
Das ist noch der alte Stand. Die neue Version verzögert sich weil ich warte bis der neue JS controller stable ist. Das aktuelle Problem ist auch durch Änderungen an der sendTo() Funktion im neuen JS controller entstanden

**Comment by Xenon-s** [comment]
bitte aktuelle Github Version testen

**Comment by aruttkamp** [comment]
Keine Devices etc. mehr da. Korrekt? ( ist nicht schlimm. möchte nur drauf hinweisen )

**Comment by Xenon-s** [comment]
Du hast nicht neu installiert, sondern drüber oder? Sollte eigentlich nicht so sein 😕

**Comment by Xenon-s** [comment]
das Problem ist, dass ich die ganze Datenstruktur des Adapters ändern musste, damit sie mit dem neuen JS Controller 5.x klar kommt. Das setzt jetzt aber leide eine neue Instanz vorraus, die alte wird nicht mehr sauber laufen können. Das ganze wird ein breaking Change Update auf Version 2.x werden

**Comment by aruttkamp** [comment]
Alles gut. Kein Problem

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kuckuckmann** [comment]
Ich hab den 2.xDEV gerade installiert mit dem Link von weiter oben. Sieht gut aus, läuft Flüssig, Anzeige ist sauber auch in dunklen Farben. Sehr guter Ansatz :-)

Jetzt die Aber:
- Meine Geräte und deren Schwellwerte sind zwar noch da, aber keine Kommunikationsdefinitionen (kein telegram, keinMail, etc)
- der Adapter startet nicht

Bin jetzt zurück auf den 1.2.9 jedoch scheint meine Konfig jetzt komplett durcheinander :-(

**Comment by Xenon-s** [comment]
@kuckuckmann die 2.Dev ist nicht lauffähig. Du musst die normale Master installieren, danach dann eine neue Instanz anlegen und diese nutzen. Deine Werte aus der alten Instanz musst du einmalig händisch übertragen

**Comment by kuckuckmann** [comment]
Ok, passt. ich werde jetzt einfach warten, bis Du soweit bist.

**Comment by Xenon-s** [comment]
Die Version hier ist eigentlich lauffähig

https://github.com/Xenon-s/ioBroker.device-reminder

Wie gesagt, du musst eine neue Instanz anlegen und Werte dann aus der alten Instanz von Hand übertragen. Alternativ Adapter komplett deinstallieren und neu installieren. Da wird in der neuen Version definitiv kein Weg dran vorbei führen

**Comment by Xenon-s** [comment]
neue Version 2.0.1 auf npm, damit sollte der Fehler behoben sein
