### ISSUE TITLE
Benachrichtigungsempfänger via DP konfigurierbar

### ISSUE THREAD

**Issue by Smo-RBR** [Xenon-s/ioBroker.device-reminder#274]
Es wäre ein schönes Feature, wenn man auch bei Pushover Benachrichtigungen Datenpunkte wählen könnte. Dann kann man im VIS eine Auswahl haben, wer benachrichtigt wird.

**Comment by Xenon-s** [comment]
Die eigentliche Konfiguration läuft über die Instanzeinstellungen und das werde ich auch nicht ändern. 
Hintergrund: Wenn man jetzt anfängt in Datenpunkten und parallel im Admin zu konfigurieren, ist das ein riesen Durcheinander und Code-technisch auch nicht umsetzbar, ohne die gesamte Adapterstruktur neu schreiben zu müssen. Wenn man die Instanzeinstellungen speichert, werden alle relevanten Daten ins Backend geschrieben. Mit diesen Daten arbeitet der Adapter nun. Ändert man in den Datenpunkten nun die Empfänger, passen sie beim nächsten Aufruf der Instanzeinstellungen nicht mehr mit den Daten überein und es kommt zu Störungen.
Wenn solche Dinge gewünscht sind, muss man mit eignen Skripten auf die Datenpunkte des Adapters reagieren und dann Nachrichten individuell versenden
