### ISSUE TITLE
Possibility to control another power adapter for washing machines (water valve)

### ISSUE THREAD

**Issue by Elluminatus** [Xenon-s/ioBroker.device-reminder#283]
It would be nice if you could implement another power supply control for the washing machine. So you can control the power of the washing machine AND can open and close the water valve with a sonoff or something else.

Greetings and thank you.
Elluminatus

**Comment by Xenon-s** [comment]
No, the adapter is not intended for this purpose. Here you have to work with an extra script and react on the status
