### ISSUE TITLE
2 Bugs in version 1.2.9 and 2.0.1 from IOB forum

### ISSUE THREAD

**Issue by EuloTV** [Xenon-s/ioBroker.device-reminder#297]
Hi, wie im Forum schon beschrieben sind mir 2 Bugs aufgefallen.

Ich packe beide jetzt mal hier in den Issue rein.

**Bug1:**
Bei Adapter Version 1.2.9 die man über den IOB Adapter Store ziehen kann tritt folgender Bug auf: 

Im Konfiguartions Menü welches über "Instanzen -> Device-reminder" aufgerufen wird. Sind keine eingaben möglich. Außer dem Logo sieht man nichts auf der Seite.

Siehe Link: 
[Link 1](https://forum.iobroker.net/topic/40573/test-adapter-device-reminder-v-1-x/577)

**Bug2:**
Bei der Version 2.0.1 die man über Github Downloadet entsteht ein Problem welches von einem anderen User im Forum hervorragend geschildert wurde. Kurz gesagt: Man kann seine Eingaben nicht Speichern. 

Siehe Link:
[Link 2](https://forum.iobroker.net/topic/40573/test-adapter-device-reminder-v-1-x/583?_=1694956884325)

Meine Versionen:
- Adapter:
> Bug 1: 1.2.9
> Bug 2: 2.0.1
- JS-Controller: 
> 5.0.12
- Node:
> 18.17.1
- NPM:
> 9.6.7

Mfg Eulo

**Comment by Czarno13** [comment]
Hallo....bei mir genau die gleichen Probleme, nur das Logog zu sehen, keine Einfgaben möglich
Version: 1.2.9
Node.js v18.17.1
JS-Controller 5.0.12
NPM 9.6.7

**Comment by Xenon-s** [comment]
Die 1.2.9 läuft nicht mehr in Verbindung mit JS controller 5.x und wird auch nicht mehr weiter entwickelt. Die 2.x ist soweit lauffähig, aber dort erscheint unter bestimmten Bedingungen nicht immer der Speicher Button. An dem Thema bin ich dran

**Comment by Hohenbostler** [comment]
Hallo, 

leider habe ich das selbe problem . Ich kann die EInstellungen nicht speichern. 

Wenn ich innerhalb der Instanz aber das Design vom iobroker wechsel sehe ich ganz kurz die entsprechenden Button.

Dann verschwinden sie wieder. 
![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/42488069/40390cb1-acb1-42cc-8bf1-ae91434e9582)

**Comment by flotux2** [comment]
@Xenon-s: Kannst du ungefähr abschätzen, wann du dir das anschauen kannst? ;-)

Der Adapter ist halt schon sehr praktisch, wenn man nicht alles selbst mit JavaScript oder Blockly umsetzen muss. 
Es wäre schade, wenn man den Adapter nicht mehr nutzen könnte.

**Comment by Xenon-s** [comment]
Ich bin aktuell dabei. Da ich aber eine weiter entwickelte Version auf github habe, in der noch einiges an Arbeit steckt, wirds noch etwas dauern

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen

**Comment by flotux2** [comment]
@Xenon-s: 
Ich habe die neue Version 2.1.0 getestet. Irgendwie funktioniert das bei mir aber noch nicht. Ich konnte zwar die Sensoren zuordnen und auch die Telegram Benachrichtigung konfigurieren und alles so speichern, dass es anschließend wieder korrekt angezeigt wird. Allerdings löst es bei mir keine Benachrichtigung aus. Auch im Log sehe ich keine Einträge, wenn z.B. Spülmaschine die anläuft. 

Allerdings könnte es auch an meinen Blitzwolf ZigBee Plugs liegen. Hier bin ich mir gerade nicht sicher, ob die Werte bei Power korrekt liefern. Ich muss mir das am Wochenende näher anschauen. Dann kann ich zurückmelden, ob es am Adapter oder den Geräten liegt.

**Comment by Xenon-s** [comment]
Ich habe die neue Version fast fertig. Problem ist, dass die alte Datenstruktur immer wieder Fehler verursacht hat, weshalb ich da grundlegend bei musste. Ich hatte zuerst gedacht, dass ich das migrieren kann, aber da ja auch noch viele auf der 1.2.9 unterwegs sind, andere aber auf den neueren Versionen, ist das nicht möglich.

Deine beschriebene Problematik kann durchaus am Adapter liegen. Auch die neue Version wird mit Sicherheit noch einige kleinere Probleme haben, da ich da grundlegende Dinge verändert habe, damit endlich Ruhe ist.

Nach derzeitigem Stand gehe ich nur noch von einer neuen Installation aus, da ich mehrere verschiedene alte Versionen probiert habe zu updaten. Leider gab's danach immer wieder andere Probleme

**Comment by Hohenbostler** [comment]
Moin. ich habe leider seit dem Update das Problem das mein Adapter dauerhaft auf gelb bleibt. Hier mal ein Screen vom Protokoll im Debug modus vom Adapter.

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/42488069/96689844-cf2a-4dd7-93fd-e4fcc51ced8c)

**Comment by Xenon-s** [comment]
Neue Version verfügbar. Bitte den Changelog beachten!

**Comment by Hohenbostler** [comment]
> Neue Version 2.1.2 auf github verfügbar. Bitte den Changelog beachten!

erledigt. Adapter bleibt leider trotzdem Gelb.

**Comment by Xenon-s** [comment]
Der bleibt solange gelb, bis du Geräte angelegt hast

**Comment by Xenon-s** [comment]
Neue Version 3.0.0 auf github. Bitte Hinweise beachten und am besten den Adapter neu installieren, sollte man nicht die Version 2.1.2 installiert haben

**Comment by Hohenbostler** [comment]
Morgen, ok dann scheint es bei mir wohl ein anderes Problem mit dem Adapter zu sein. Geräte sind angelegt und auch verknüpft mit Alexa und Whatsapp. Dennoch gibt es bei objekte keine Einträge und der Adapter bleibt gelb.

**Comment by Xenon-s** [comment]
Bevor wir hier aneinander vorbei reden. Welche Version hast du installiert? Und hast du die alte Version vorher entfernt und dann die neue Version installiert?

**Comment by Hohenbostler** [comment]
Ich nutze die Version 3.0.0 . Ja den alten Adapter habe ich vorher deinstalliert. 

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/42488069/9073e0ed-bda1-4f71-95b8-68cf3571f922)

**Comment by Xenon-s** [comment]
Zeig mal Screenshots von deinen Geräten und den verknüpften Geräten

**Comment by Hohenbostler** [comment]
Morgen, hier die Bilder.

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/42488069/0a5b52ae-420e-494e-8ba9-3c2a5aa5aff1)

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/42488069/4d22af93-4eec-4957-b8a4-0d84bc7812fe)

**Comment by Xenon-s** [comment]
Aktiviere mal den Expertenmodua unter Objekte
Dann gehst du auf Adapter - Device-Reminder - und dann rechts auf den Stift beim Ordner 0

Dann öffnet sich eine Datei im json Format. Irgendwo steht "linkes-devices", davon brauche ich einen Screenshot.
Im forum habe ich dazu auch nochmals eine Anleitung

https://forum.iobroker.net/topic/68936/test-adapter-device-reminder-v-3-x/39

**Comment by Hohenbostler** [comment]
Würde ich gerne. Aber anscheinend hat meine Instanz keinen bearbeitungsmodus.

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/42488069/d792c96a-0c10-49e0-8426-72311df573fc)

**Comment by Hohenbostler** [comment]
Also mein Problem kann hier geschlossen werden. Ich habe nochmal alles komplett entfernt inkl dem adapter. Dann neu angelegt und nun sehe ich die Objekte.
