### ISSUE TITLE
Version 2.0.1 Stromschalter nicht optional

### ISSUE THREAD

**Issue by bzrker** [Xenon-s/ioBroker.device-reminder#298]
Beim Anlegen eines Gerätes ist das "Stromschalter" Feld nun offenbar ein Pflichtfeld, obwohl es in der Hilfe als optional angegeben ist.

![grafik](https://github.com/Xenon-s/ioBroker.device-reminder/assets/20478994/ff0bc62c-1b76-4809-8b14-48026ca62091)

**Versions:**  
 - Adapter version: 2.0.1
 - JS-Controller version: 5.0.12
 - Node version: 9.6.7

**Comment by Xenon-s** [comment]
Ist bekannt und in der neuen Version die in nächster Zeit raus kommt auch gefixt. Ich habe aber kein genaues Datum dazu
