### ISSUE TITLE
Device Reminder Instance Configuration is empty

### ISSUE THREAD

**Issue by aortmannm** [Xenon-s/ioBroker.device-reminder#299]
Hello,

my devices reminders are still working and my telegram messages are sent when I;m using the devices that I have configured month's ago but I want to add a new one and it seems like the GUI is broken.

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/3414298/91d1d09c-e821-46a7-a209-a049d545b706)

What I tested so far:

```
iob upload device-reminder
iob stop
iob fix
iob start
```
same result as before.

All is stable so Admin in Version 6.10.1 and Device-Reminder in Version 1.2.9

**Comment by vr6syncro** [comment]
bei mir ebenso

**Comment by Cynric10** [comment]
same

**Comment by voyage200** [comment]
bei mir das gleiche Problem

**Comment by Dexebal** [comment]
+1

**Comment by Xenon-s** [comment]
Die 2.0.1 behebt das Problem, ist aber nicht stable. Dazu gab's schon ein issue, bitte in Zukunft vorher prüfen, bevor ein neues issue erstellt wird
