### ISSUE TITLE
Adapter geht nur wenn path switch on/off angegeben.

### ISSUE THREAD

**Issue by fabiankrauss** [Xenon-s/ioBroker.device-reminder#3]
**Describe the bug**  
Er wirft mir folgende Fehler, wenn ich keinen Datenpunkt unter Switch angebe.
Ich möchte den Adapter für die "Überwachung" meiner Spülmaschine testen. An der habe ich garkeinen Schaltkontakt wie bei einer Zwischensteckdose. Also wollte ich auch keine angeben. 
Jetzt habe ich das Relay von Shelly EM angegeben auch wenn es keine Funktion hat.

**Expected behavior**  
Adapter funktioniert auch wenn kein Switch angegeben ist.

**Screenshots & Logfiles**  
device-reminder.0 | 2020-10-31 17:53:38.352 | error | at async Template.onReady (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:58:31)
-- | -- | -- | --
device-reminder.0 | 2020-10-31 17:53:38.352 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
device-reminder.0 | 2020-10-31 17:53:38.352 | error | at Template.inputPruefen (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:100:32)
device-reminder.0 | 2020-10-31 17:53:38.352 | error | at Template.getForeignObjectAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1584:16)
device-reminder.0 | 2020-10-31 17:53:38.352 | error | at new Promise (<anonymous>)
device-reminder.0 | 2020-10-31 17:53:38.352 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1585:16
device-reminder.0 | 2020-10-31 17:53:38.352 | error | at Template.getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2854:17)
device-reminder.0 | 2020-10-31 17:53:38.352 | error | at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:482:19)
device-reminder.0 | 2020-10-31 17:53:38.352 | error | (24305) Error: The id is empty! Please provide a valid id.
device-reminder.0 | 2020-10-31 17:53:38.350 | error | (24305) unhandled promise rejection: The id is empty! Please provide a valid id.
Unhandled | 2020-10-31 17:53:38.350 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Versions:**  
 - Adapter version: 0.1.2
 - JS-Controller version: 3.1.4
 - Node version: v12.16.3
 - Operating system: debian auf proxmox

**Comment by Xenon-s** [comment]
im nächsten patch fliegt das raus, dann gehts auch ohne. dnake für den Hinweis
