### ISSUE TITLE
Not possible to add devices to the reminder v1.2.9

### ISSUE THREAD

**Issue by Maschine20** [Xenon-s/ioBroker.device-reminder#313]
**Describe the bug**  
The buttons are missing in the view "Instanzen" to add a device.

**To Reproduce**  
1. Go to instances
2. Try to add an device. There are no buttons

**Expected behavior**  

**Screenshots & Logfiles**  
![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/89000090/ac69dfc3-f96b-43a2-b587-311573c85123)

**Versions:**  
 - Adapter version: v1.2.9
![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/89000090/7e17c761-c09e-42d8-9152-4c153b530b68)

**Comment by Xenon-s** [comment]
https://github.com/Xenon-s/ioBroker.device-reminder/issues/299
