### ISSUE TITLE
Neuste Github Version 2.1.2 nicht in den Instanzen zu sehen

### ISSUE THREAD

**Issue by afarud** [Xenon-s/ioBroker.device-reminder#320]
Hallo, 
nach einigen Seiten lesen, habe ich den Adapter deinstalliert und die Version von Github per Katze installiert. 
Leider sehe ich nun die Instanz nicht bei den Instanzen. 

Ich sehe jedoch unter Adapter das er installiert ist: 2.1.2 und auch unter Objekten sehe ich den admin Ordner unter device-reminder. 

<img width="166" alt="device-reminder" src="https://github.com/Xenon-s/ioBroker.device-reminder/assets/50336616/3fb6e657-0925-4f2e-b9d1-1bcddbc2aa45">

**Versions:**  
 - Adapter version: 2.1.2
 - JS-Controller version: 5.0.12
 - Node version: v18.17.1
 - Operating system: Linux ubuntu server 

Ich wollte nur schnell was ändern in der Konfiguration wegen einem neuen Trcockner und sitze nun 2 h an dem Problem. 
Ich möchte nicht wissen, wie lange man fürs Programieren und testen verbraucht. Geroßen Respekt von mir.

Gruß
afarud

**Comment by Xenon-s** [comment]
Adapter, welche über github installiert werden, legen keine Instanz automatisch an. Das musst du selber unter Adapter machen
Alternativ, wenn du dich damit nicht auskennst, warten bis der Adapter ina iobroker Repo kommt. Das kann noch ein paar Tage dauern, da aktuell immer noch kleinere Fehler auftauchen

![Screenshot_20231019_211625_Chrome](https://github.com/Xenon-s/ioBroker.device-reminder/assets/65488191/c023f144-81b5-4c57-bc9a-9ae693da462b)

**Comment by afarud** [comment]
Vielen Dank für die Info, bin leider nicht so erfahren und war mir nicht sicher ob ich das melden soll. 
Sorry. 
Ich werde warten und mich auf dem laufenden halten. 
Dir viel Erfolg und wirklich großen Respekt für die Arbeit. Werde auch gleich Paypal was rausschicken. 
Gruß
afarud

**Comment by Xenon-s** [comment]
Die neue Version 3.0.0 liegt auf github und darf gerne von dir getestet werden 😉
Danke dir!
