### ISSUE TITLE
Nach Adapter Installation erscheint bei mir nur Please activate the device-reminder.0 instance!

### ISSUE THREAD

**Issue by chrisdu** [Xenon-s/ioBroker.device-reminder#323]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
nach installation des Adapters --> Please activate the device-reminder.0 instance!
Nachdem ich dann den Adapter schließe und wieder öffne erscheint eine leere Seite.
ich wollte schon die Version 3.0.0 installieren aber das funktioniert bei mir auch nicht. (hab schon auf repositories beta umgestellt)
es wird mir immer die version 1.2.9 angeboten.

![device-reminder01](https://github.com/Xenon-s/ioBroker.device-reminder/assets/4033905/602efe8a-f8b7-4842-9fd0-8d413511b2f3)

![device-reminder02](https://github.com/Xenon-s/ioBroker.device-reminder/assets/4033905/d1f72df0-6e11-42c3-875e-9130fc73b12a)

**Versions:**  
 - Adapter version: <1.2.29>
 - JS-Controller version: <js-controller-version> 5.0.12
 - Node version: <node-version>  v16.20.2
 - Operating system: <os-name> raspberry debian Bullseye

**Additional context**

**Comment by Xenon-s** [comment]
Die V1.2.9 ist in Kombi mit dem JS 5.x nicht lauffähig. Deinstallier den Adapter vollständig und installiere die V3.0.
Und danach startest du den Adapter bevor du ihn konfigurieren willst

**Comment by chrisdu** [comment]
Danke für die schnelle Hilfe, aber mir wird die Version 3.0. nicht angeboten auch nicht als Beta. Wie kann ich den Adapter sonst installieren?

**Comment by Xenon-s** [comment]
Was machst du da? Wie hast du installiert? Und was willst du mit sudo?
Der Adapter ist in der latest. Word er dir da nicht angezeigt, ist es wahrscheinlich ein Anzeigefehler deines Browsers.
Hast du ihn per github insto? Wenn ja, direkt wieder löschen. Der stand auf github ist nicht der gleiche wie die V3.0.0!

**Comment by Xenon-s** [comment]
Was machst du da? Wie hast du installiert? Und was willst du mit sudo?
Der Adapter ist in der latest. Word er dir da nicht angezeigt, ist es wahrscheinlich ein Anzeigefehler deines Browsers.
Hast du ihn per github insto? Wenn ja, direkt wieder löschen. Der stand auf github ist nicht der gleiche wie die V3.0.0!

**Comment by chrisdu** [comment]
hallo, mir wird wie schon oben geschrieben nur die Version 1.2.9 angeboten. Habs mit Opera, chrom und firefox versucht.
Hab dann eben die V3.0.0 via Github installiert und wollte über die Konsole starten da ich den Adapter unter iobroker nicht gesehen hab.

**Comment by Xenon-s** [comment]
Wenn man per github installiert muss man manuell eine Instanz anlegen.
Der Adapter ist gerade auch in die stable gegangen, sollte spätestens morgen da angezeigt werden

**Comment by chrisdu** [comment]
Bitte wie legt man manuell eine Instanz an?
Danke für deine Hilfe

**Comment by Xenon-s** [comment]
kein bug, closed
