### ISSUE TITLE
Please update testing

### ISSUE THREAD

**Issue by mcm1957** [Xenon-s/ioBroker.device-reminder#325]
Please update standard testing (https://github.com/Xenon-s/ioBroker.device-reminder/pull/217).  PR is older than a year in the meantime.

Please include node 20 into tests as node 20 is already released as stable verion unless this adapter fails using node 20. In this case please create a issue and try to fix ist as soon as possible.

Please add engine>16 into package.json when updateing adapter core to 3.x.x as adapter core 3.x.x fails at node 14 and earlier.

**Comment by mcm1957** [comment]
No problem - I wrote ... for the next release ...
It completly ok to provide a hoitfix for js-controller now without minimum delay. THANKS a lot.

**Comment by Xenon-s** [comment]
fixed in 3.0.1
