### ISSUE TITLE
Werte ohne Interface einsehen in 1.2.9?

### ISSUE THREAD

**Issue by DickenSerm** [Xenon-s/ioBroker.device-reminder#326]
Hey, das die 1.2.9 mit dem neuen js-controller nicht mehr läuft und man nicht mehr in die Adaptereinstellungen kommt, ist mir bekannt.

Nun soll ich ja die alte Version deinstallieren und die 3.0.0 neu installieren.

Allerdings habe ich diverse Anpassungen an meinen Werten vorgenommen und würde die wirklich gerne vorher einsehen können um diese in der neuen Version auch wieder zu verwenden.

Gibt es eine Möglichkeit an die festgelegten Werte zu kommen ohne über die Adaptereinstellungen zu gehen?

LG Dicken

**Comment by Xenon-s** [comment]
Hey, ja gibt es. Ich bin aktuell unterwegs und kann keine Screenshots posten

Du aktivierst unter Objekte die Expertenansicht. Danach gehst du auf "Adapter-> Device-Reminder" und beim Instanz Ordner, wahrscheinlich 0,ist ein Stift. Auf den klickst du drauf und es öffnet sich ein json

Da findest du dann custom und default wenn du etwas runter scrollat. Darin stehen dann diene Werte.

Ich hätte das Ganze mal in die readme packen sollen...

Im. Forum unter test Adapter Device-Reminder V3.0.0 findest du dazu auch Screenshots

**Comment by Xenon-s** [comment]
https://forum.iobroker.net/topic/68936/test-adapter-device-reminder-v-3-x/39?_=1698421527795

**Comment by DickenSerm** [comment]
Danke, ah jetzt hab ichs gefunden. Hatte immer bei "Adapter-> Device-Reminder" geschaut, da war aber kein Stift.
Muss natürlich unter "System -> Adapter-> Device-Reminder" nachschauen. Da wurde ich jetzt auch fündig. Danke für die schnelle Antwort :)

**Comment by Xenon-s** [comment]
Es war leider nicht wirklich möglich die Daten zu Migrieren. Die alte Version hat immer mal wieder Datenmüll angelegt, der dann dazu geführt hätte, dass es beim Migrieren knallt.

Ich finde die Lösung der Neuinstallation auch nicht gut und hab lange versucht eine Lösung dafür zu finden. Kann man auch daran sehen, dass die Version von 1.2.9 auf 3.0.0 gesprungen ist. Die ganzen 2er Versionen haben immer wieder Ärger gemacht, weil die Daten dort migriert wurden und es dann an verschiedenen Stellen wieder zu Datenmüll kam

**Comment by DickenSerm** [comment]
Ach alles gut, hauptsache man weiß wie man dran kommt, die paar Werte kann ich auch von Hand wieder anlegen :)
