### ISSUE TITLE
device-reminder.0.info.connection

### ISSUE THREAD

**Issue by bambi-arch** [Xenon-s/ioBroker.device-reminder#328]
Folgende Meldung erscheint im Protokoll

State "device-reminder.0.info.connection" has no existing object, this might lead to an error in future versions

V3.0

**Comment by Xenon-s** [comment]
Ist bereits bekannt, sollte mit dem nächsten Patch behoben sein

**Comment by Xenon-s** [comment]
fixed in 3.0.1
