### ISSUE TITLE
Geräte werden in Ansicht Instanzen nicht mehr angezeigt

### ISSUE THREAD

**Issue by Haifeif** [Xenon-s/ioBroker.device-reminder#329]
**Describe the bug**  
Ich überwache 4 Geräte mit dem Adapter. Vor einigen Wochen fiel mir auf, das in der Instanzen Ansicht keine Geräte mehr sichtbar sind. Der Adapter funktioniert aber. Daher habe ich das Ganze erstmal vergessen.

Jetzt beobachte ich einen Wert, der sich seltsam verhält, brauche dazu aber "Zugriff" auf die Geräte!

**To Reproduce**  
1. Go to 'Intanzen'
2. Click on Device-Reminder.0
3. See pic 1

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/59795191/c9972fd7-b57f-4a8a-827c-95dc62cadc2d)

5. See error

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: v1.2.9
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1
 - Operating system: Debian GNU/Linux 11 bullseye

**Comment by Xenon-s** [comment]
Das darf doch echt nicht mehr war sein. Wie oft soll das issue noch erstellt werden? Es gibt seit Wochen eine neue Version, mittlerweile sogar im stable

**Comment by Haifeif** [comment]
Sorry, aber das ein neuer Adapter verfügbar ist, tauchte erst Tage nach meiner Meldung auf. Alles gut, der neue scheint zu funktionieren. Falls ich bei einer Doku helfen kann, einfach Bescheid sagen. LG
