### ISSUE TITLE
Namensfeld für "Benutzerdefinierte Gerätetypen"

### ISSUE THREAD

**Issue by Gwenselah** [Xenon-s/ioBroker.device-reminder#337]
custom1 bis custom10 ist nicht besonders aussagekräftig, Mir ist bekannt, dass die Namen selbst nicht geändert werden können. Aber ein weiteres Feld wie "eigener Name" oder "Kommentar" wäre hilfreich, damit man direkt sieht, wofür man custom1 verwendet hat.

**Comment by DerT94** [comment]
+1

**Comment by Xenon-s** [comment]
schaue ich mir an
