### ISSUE TITLE
Keine Daten angezeigt

### ISSUE THREAD

**Issue by LocoR9** [Xenon-s/ioBroker.device-reminder#338]
In den Change Notes zu v.3 steht das man die Werte aufschreiben soll bevor man das Update macht, leider werden bei mir keine Daten mehr angezeigt und ich habe bei einigen Geräten die Werte angepasst. Kommt man noch an die Daten?

![Screenshot 2023-11-05 131725](https://github.com/Xenon-s/ioBroker.device-reminder/assets/122697750/06e4f1b2-212a-4ec4-a041-4c431dca4604)

**Comment by Black-Hawk112** [comment]
das würde mich auch interessieren :-D 
Finde leider auch nichts ...

**Comment by Xenon-s** [comment]
https://github.com/Xenon-s/ioBroker.device-reminder/issues/326
