### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Hohenbostler** [Xenon-s/ioBroker.device-reminder#339]
Hi leider bin ich nicht so tief in der Materie um zu wissen wo dieser Fehler herkommt.

Aber ich bekomme folgende Error Einträge in den iobroker. 

`<html><body>

device-reminder.0 | 2023-11-08 08:14:01.361 | warn | State "device-reminder.0.info.connection" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
device-reminder.0 | 2023-11-08 08:13:59.726 | info | starting. Version 3.0.0 in /opt/iobroker/node_modules/iobroker.device-reminder, node: v18.17.1, js-controller: 5.0.12
device-reminder.0 | 2023-11-08 08:13:21.537 | info | terminating
device-reminder.0 | 2023-11-08 08:13:20.881 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
device-reminder.0 | 2023-11-08 08:13:20.787 | info | terminating
device-reminder.0 | 2023-11-08 08:13:20.541 | error | Converting  circular structure to JSON    --> starting at object with  constructor 'Timeout'    \|     property '_idlePrev' -> object with  constructor 'TimersList'    --- property '_idleNext' closes the circle
device-reminder.0 | 2023-11-08 08:13:20.541 | error | TypeError:  Converting circular structure to JSON    --> starting at object with  constructor 'Timeout'    \|     property '_idlePrev' -> object with  constructor 'TimersList'    --- property '_idleNext' closes the circle     at JSON.stringify (<anonymous>)    at sendMsg  (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:1144:47)
device-reminder.0 | 2023-11-08 08:13:20.498 | error | unhandled  promise rejection: Converting circular structure to JSON    -->  starting at object with constructor 'Timeout'    \|     property  '_idlePrev' -> object with constructor 'TimersList'    --- property  '_idleNext' closes the circle
device-reminder.0 | 2023-11-08 08:13:19.488 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

</body>
</html>`

**Comment by Xenon-s** [comment]
Please use the bug template here on Github
