### ISSUE TITLE
Gerät wird bei Ausschaltverzögerung nicht abgeschaltet

### ISSUE THREAD

**Issue by guergen1** [Xenon-s/ioBroker.device-reminder#345]
Mit ist grade aufgefallen, dass die Ausschaltverzögerung nicht funktioniert.
Will heissen, der DR meldet "Fertig" und dann soll das Gerät nach 10 Minuten abgeschaltet werden, macht es aber nicht.
Ich habe eine Gegenprobe gemacht:
Habe ich ein Gerät was beim Ende direkt abgeschaltet werden soll geht es immer zuverlässig. Setze ich bei dem Gerät eine Verzögerung von 1 Minute, wird es nicht abgeschaltet.

**Versions:**  
 - Adapter version: 3.0.0
 - JS-Controller version: 5.0.16
 - Node version: 18.18.2
 - Operating system: debian

**Comment by Xenon-s** [comment]
teste mal die aktuelle NPM (3.0.1) oder die aktuelle github 3.0.2-beta

**Comment by Xenon-s** [comment]
habs getestet, funktioniert in der 3.0.3-beta auf github
