### ISSUE TITLE
Signal: Telefonnummer nicht optional und internationale Rufnummer +49…. wird nicht akzeptiert.

### ISSUE THREAD

**Issue by manf323** [Xenon-s/ioBroker.device-reminder#346]
Bei Meldung an Signal ist die Eingabe einer Telefonnummer nicht optional.
Auch wird die Eingabe +49… für 0049… nicht akzeptiert.

Adapter v3.0.1

**Comment by Kaiman77** [comment]
Gleiches Problem hier - ich habe von Signal auch keine Telefonnummer sondern eine ID als Nummer erhalten, diese kann man für Signal nicht eintragen. Da das Feld aber auch nicht optional ist, kann ich Signal im device reminder garnicht nutzen.

**Comment by Xenon-s** [comment]
aktuelle github version testen

**Comment by manf323** [comment]
Eingabe der Telefonnummern funktioniert jetzt.Aber, bei  Status „Stop“ wird der Datenpunkt nicht übernommen, es kommt auch keine Signal-Meldung.Am 22.12.2023 um 08:31 schrieb Xenon-s ***@***.***>:﻿
aktuelle github version testen

**Comment by Xenon-s** [comment]
Verstehe nicht, was du meinst

**Comment by manf323** [comment]
Habe unter Starttext einen Datenpunkt angegeben. Die mittels Script erzeugte Meldung (Geräte Status = Start) wird über Signal ausgegeben.Unter Endtext ist ein anderer Datenpunkt angegeben. Auch hier wird mittels Script eine Meldung eingetragen (Geräte Status = Stop). Die wird aber nicht mit Signal ausgegeben.Am 22.12.2023 um 20:11 schrieb Xenon-s ***@***.***>:﻿
Verstehe nicht, was du meinst

**Comment by Xenon-s** [comment]
Aber der Gerätestatus wird schon richtig erkannt?

**Comment by manf323** [comment]
Das Script zur Meldungserzeugung wird ausgeführt und der EndText-Datenpunkt wird aktualisiert.Am 22.12.2023 um 21:00 schrieb Xenon-s ***@***.***>:﻿
Aber der Gerätestatus wird schon richtig erkannt?

**Comment by Kaiman77** [comment]
Ich hab die GitHub Version jetzt getestet. Die Eingabe der Rufnummer ist jetzt optional. Wenn ich sie weglasse, kommt die Benachrichtigung problemlos. 

Frage: wofür kann man im device reminder Adapter bei Signal überhaupt eine Nummer angeben? Da der Signal Adapter aktuell eh nicht mehrere Nummern pro Instanz kann, hat das doch garkeinen Mehrwert, oder?

**Comment by Xenon-s** [comment]
ich habe die Daten einfach aus der Doku übernommen, werde die Nummer entfernen

**Comment by Xenon-s** [comment]
Nummer ist entfernt, wenn möglich die neue Version von github 3.0.3-beta testen und feedback geben :)

**Comment by Xenon-s** [comment]
mein Fehler, ich habe den Intervall noch auf 1 Sekunde anstatt auf 10 Sekunden gehabt. Wird mit dem nächsten Upload auf 3.0.4 wieder passen

**Comment by Xenon-s** [comment]
die neue Version wurde auch um TTL bei Pushover erweitert. Bei Problemen bitte neues issue, da das eigentliche Problem behoben wurde
