### ISSUE TITLE
Bekomme seit letztem update bei jedem Adapterstart eine Meldung im Protokoll

### ISSUE THREAD

**Issue by DerBorn** [Xenon-s/ioBroker.device-reminder#347]
Hallo, folgende Meldung erscheit bei jedem neustart und start des Adapters.

<html>
<body>

device-reminder.0 | 2023-11-21 14:11:54.043 | warn | State "device-reminder.0.info.connection" has no existing object, this might lead to an error in future versions
-- | -- | -- | --

</body>
</html>

Adapter ist aktuell auf Version 3.0.0
node 18.18.2
npm 9.8.1

was kann ich da tun?
oder anders, was will mir die Meldung mitteilen ?

**Comment by Xenon-s** [comment]
bitte neue github version testen
