### ISSUE TITLE
Gesamtverbrauch

### ISSUE THREAD

**Issue by Norb1204** [Xenon-s/ioBroker.device-reminder#364]
Kannst Du vielleicht noch den Gesamtverbrauch pro Start und Stopp **kontinuierlich** berechnen und in einen DP ablegen.
So könnte man den aktuellen/momentanen Gesamtverbrauch sowie den Verbrauch am Ende abfragen für spätere z.B. Vergleiche. Man hätte sich halt noch ein zusätzliches Script gespart.

**Comment by Xenon-s** [comment]
nein, wurde auch schon mehrfach begründet. Das ist nicht die Aufgabe des Adapters, dieser Überwacht nur die Zustände
