### ISSUE TITLE
Speichern Buttons verschwunden

### ISSUE THREAD

**Issue by kptkip** [Xenon-s/ioBroker.device-reminder#366]
**Describe the bug**  
Die Buttons für das Speichern der Einstellungen sind ausgeblendet und von daher können EInstellungen nicht übernommen werden.

**To Reproduce**  
1. Instanz-Einstellungen öffnen
2. Buttons nicht sichtbar (s. Screenshot)

**Expected behavior**  
Buttons sind sichtbar und aktiviert

**Screenshots & Logfiles**  
<img width="1236" alt="Bildschirmfoto 2023-12-12 um 07 56 20" src="https://github.com/Xenon-s/ioBroker.device-reminder/assets/16083703/e9abf143-a03f-4206-8662-48b90d629335">

**Versions:**  
 - Adapter version: 3.0.0
 - JS-Controller version: 5.0.12
 - Node version: 16.17.0
 - Operating system: Docker

**Additional context**  
Durch das manuelle Aktivieren und EInblenden der Buttons per Entwicklerkonsole konnte ich sie wieder einblenden und die Einstellungen speichern.
<img width="683" alt="Bildschirmfoto 2023-12-12 um 07 56 40" src="https://github.com/Xenon-s/ioBroker.device-reminder/assets/16083703/ea5d3206-d52f-4c7b-b3c0-30f766e827e0">

**Comment by kptkip** [comment]
Wenn ich mir die Liste von Bugs hier anschaue und die durchschnittliche Reaktionsgeschwindigkeit, dann muss ich mich gemäß FIFO vor Ostern 2024 wohl nicht darauf gefasst machen, dass auf diesem Kanal ein Feedback kommt...

**Comment by Xenon-s** [comment]
Sag mal, geht's noch? Ich mache das hier privat, unentgeltlich und freiwillig. Wenn ich aktuell keine Zeit, Lust oder sonstwas habe geht das niemanden was an und ich muss mich dafür auch bei niemandem rechtfertigen oder abmelden. Es ist jedem selbst überlassen, den Adapter mit zu entwickeln und einen PR zu erstellen. Wenn dich der Bug so sehr stört und dir meine Bearbeitungszeit nicht passt, bitte, behebe ihn doch einfach selbst

**Comment by skvarel** [comment]
Kann ich nicht nachvollziehen. Hier geht es. Sobald ich etwas in den Einstellungen ändere, erscheint der Button zum Speichern. 

Adapter: 3.0.0
Admin: 6.12.9
js-controller: 5.0.17
Node: 18.17.1

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/1114419/148fd22a-6051-4be4-83f5-c4b25b1fe8da)

**Comment by kptkip** [comment]
Der typische Satz eines Software-Entwicklers, wenn beim Kunden ein Fehler auftaucht:
"Also auf meinem Rechner funktioniert es" 
Antwort: " Na dann, schicken wir halt Deinen Rechner ab sofort zum Kunden."

**Comment by skvarel** [comment]
Ich bin nur einfacher Nutzer des Adapters und nicht der Entwickler.

**Comment by Jey-Cee** [comment]
Lesen, Denken und dann schreiben. Die Antwort kam nicht vom Entwickler sondern einem anderen User. 

Wenn du willst das der Bug schnell gegixt wird dann such dir einen Entwickler den du bezahlst und der das für dich macht. Aber ich bin mir sicher du bist so ein Typ der dann nicht mal bereit wäre 20€ dafür Spri gen zu lassen.
