### ISSUE TITLE
Einbindung Telegram

### ISSUE THREAD

**Issue by Ricox1975** [Xenon-s/ioBroker.device-reminder#37]
Prüfen Sie die Erweiterung um den Messenger Telegram.

**Comment by Xenon-s** [comment]
Bitte die readme lesen. Telegram ist seit der Version 0.1 bereits integriert

**Comment by Ricox1975** [comment]
ein bisschen versteckt, aber ok. 
Cooler Adapter 

Gesendet von Mail für Windows 10

Von: Xenon-s
Gesendet: Sonntag, 21. Februar 2021 09:10
An: Xenon-s/ioBroker.device-reminder
Cc: Ricox1975; Author
Betreff: Re: [Xenon-s/ioBroker.device-reminder] Einbindung Telegram (#37)

Bitte die readme lesen. Telegram ist seit der Version 0.1 bereits integriert

**Comment by Xenon-s** [comment]
Sollten die User nicht erkannt werden, in ein paar Tagen kommt ein größeres Update, was einen kleinen fix für Telegram beinhaltet

**Comment by Ricox1975** [comment]
User wurden sofort erkannt.

Gesendet von Mail für Windows 10

Von: Xenon-s
Gesendet: Sonntag, 21. Februar 2021 09:33
An: Xenon-s/ioBroker.device-reminder
Cc: Ricox1975; Author
Betreff: Re: [Xenon-s/ioBroker.device-reminder] Einbindung Telegram (#37)

Sollten die User nicht erkannt werden, in ein paar Tagen kommt ein größeres Update, was einen kleinen fix für Telegram beinhaltet
