### ISSUE TITLE
No messages over Telegramm since v3.0.0

### ISSUE THREAD

**Issue by kuckuckmann** [Xenon-s/ioBroker.device-reminder#376]
**Describe the bug**  
Over Telegramm no messages are send

**To Reproduce**  
Configure Telegramm for messages, start respective device to reach braking values, wait for message over Telegramm.

**Expected behavior**  
While reaching the braking values a Telegramm messages should be send.

**Screenshots & Logfiles**  
What is needed?

**Versions:**  
 - Adapter version: v3.0.1
 - JS-Controller version: 5.0.17
 - Node version: v18.17.1
 - Operating system: Debian

**Additional context**  
Same configuration worked at v2 of the Adapter without any issues

**Comment by Xenon-s** [comment]
I use the adapter myself and the current 3.0.1 has been in circulation as the latest version for a very long time. My notifications always arrive. Therefore, the error is definitely not due to the adapter but to your configuration

Or you need to describe the error more specifically than "no messages arrive"

**Comment by Xenon-s** [comment]
there is a 3.0.3-beta on github, you are welcome to test it and then report back
But since it is a beta, different log entries will be created

**Comment by kuckuckmann** [comment]
I installed the beta, where can I find the logs?

**Comment by Xenon-s** [comment]
They have nothing to do with what's going on in Telegram, I just wanted to point it out

**Comment by kuckuckmann** [comment]
Ok. Any chance to get you to a talk to Discord f.e.?
I think there is sth. curiose with the states

**Comment by Xenon-s** [comment]
Iobroker discord

xenon_s

**Comment by kuckuckmann** [comment]
Ich ziehe alles zurück. Ich weiß nicht warum, aber bzgl. Telegramm geht alles wieder.
Bitte den Fall CLOSEN.

Entschuldigt die Unannehmlichkeiten.

**Comment by Xenon-s** [comment]
Alles gut, immerhin meldest du Dinge, die deine Meinung nach falsch laufen 😉
