### ISSUE TITLE
Telegram Accounts zur Auswahl anbieten

### ISSUE THREAD

**Issue by Klaus-Lucas** [Xenon-s/ioBroker.device-reminder#378]
Um Tippfehler zu vermeiden, wäre es hilfreich, wenn der Adapter in 
![grafik](https://github.com/Xenon-s/ioBroker.device-reminder/assets/36620907/4c3d0e94-81c1-4fe1-bd0d-73577ced3bd1)
die Telegram Accounts als DropDown-Feld zur Auswahl stellen würde. Nach der Wahl des Accounts könnten dann 
***username/firstname*** und ***Chat ID*** übernommen werden.

**Comment by Xenon-s** [comment]
Hallo, das war bis zur Version 3.0 so und hat ständig Ärger gemacht. Deswegen habe ich es auf diese Art geändert.

**Comment by Klaus-Lucas** [comment]
Ah ok, wäre es dann möglich eine Testnachricht per Schaltfläche zu schicken, damit man seine Eingaben prüfen kann?

**Comment by Xenon-s** [comment]
Du musst nur einen angeben, entweder user Name oder first Name. Sollte in der Doku eigentlich auch so stehen.

Für den test Button mach mal bitte neues issue auf, die Idee hatte ich auch schon mal gehabt

**Comment by Klaus-Lucas** [comment]
Das steht in der Doku:
`Username/Firstname: Der im Telegram-Adapter hinterlegte Name`
Für mich war da nicht klar, dass sich es sich um einen "entweder oder" - Eintrag handelte.
Auch verlangst du die ID. Benötigt man für das Versenden beides oder reicht z.B. die ID nicht allein aus?
