### ISSUE TITLE
Schaltfläche zum Initieren einer Testnachhricht in der Telegram-Definition

### ISSUE THREAD

**Issue by Klaus-Lucas** [Xenon-s/ioBroker.device-reminder#379]
Wäre es möglich eine Schaltfläche in dem jeweiligen Telegram-Eintrag zu platzieren, mit dem man dann eine Testnachricht initieren kann? Damit ließe sich dann die gemachten Einträge überprüfen.

**Comment by Xenon-s** [comment]
Baue ich für jede Benachrichtigung ein

**Comment by Klaus-Lucas** [comment]
Statt einer Schaltfläche könnte ich mir auch eine Checkbox vorstellen. Wenn man dann `Prüfen` wählt werden an alle angehackten Accounts eine Testnachricht geschickt.

**Comment by Xenon-s** [comment]
V 3.1.0
