### ISSUE TITLE
Schwellwert Standby

### ISSUE THREAD

**Issue by Megawaldi** [Xenon-s/ioBroker.device-reminder#38]
Hallo Xenon,
Leider haber ich bei deinen Erweiterungen gelesen, das du 
Schwellwert Standby einfügen -> mit "kommt nicht" markiert hast.

Der Wert von 1w ist bei meiner Waschmaschine/Trockner leider zu hoch.
Deswegen fällt bei mir der Status nach einem erfolgreichen Waschgang/Trocknergang sofort auf "aus".
Die beiden Geräte sind im Standby bei 0.2-0.3w.
Ich benötige aber den Standby state um einen Alexa Ansagen Loop zu starten, der dann mit dem Status "aus" wieder beendet wird. Fällt der State sofort auf "aus", kommt kein Ansagen loop.
Vieleicht willst du ja nochmal darauf herumdenken.
Danke dir

**Comment by Xenon-s** [comment]
Hallo, ich baue gerade einen Ansageloop mit in den Adapter ein. Würde das reichen? Der loop würde über einen externes Signal beendet werden (Datenpunkt)

**Comment by Megawaldi** [comment]
Hallo. Das bringt mir leider nichts. Ich habe verschiedene scripte die auf den einen Trigger lauschen. Das geht von alexa ansagen über Licht und und verschiedene andere Steuerelemente. Ich hatte vorher 4 verschiedene stati. (An/aus/waschen/fertig)

**Comment by Xenon-s** [comment]
Ich schaue es mir nochmal an. Auf die Schnelle kannst du ein kleines Script bauen, welches deine Werte immer +1 Watt rechnet und in einen neuen dp schreibt. Damit hättest du vorübergehend erstmal das Problem behoben. Update kann noch Noch etwas dauern

**Comment by Megawaldi** [comment]
Okay ich probier das mal

**Comment by Megawaldi** [comment]
Hallo Xenon. Ich hab jetzt ein bisschen rumprobiert. das mit dem neuen DP hat funktioniert. Da ich aber verschiedene Werte für Waschmaschine und Trockner habe, ist die Lösung für mich zwar funktional aber nicht so "schön".
Was ich jetzt  für mich gemacht habe:
1. ich habe in den Objekten des Adapters jedem Typ eine zusätzliche Variable gegeben:
"customTypeIDFinal": {
      "21": {
        "name": "waschen",
        "startVal": "30",
        "endVal": "15",
        "startCount": "5",
        "endCount": "65",
       "offVal": "0.3"           <----
      },
      "22": {
        "name": "trocknen",
        "startVal": "120",
        "endVal": "15",
        "startCount": "5",
        "endCount": "50",
       "offVal": "2"              <----
      },
      ....
  2. im "main" hole ich mir die Variable und übergebe die an das jeweilige Gerät im Konstruktor.
  so habe ich verschiedene Werte für verschiedene Geräte.
  Den "off Wert" hab ich dann statt der 1 im Code für die Prüfung gesetzt ob das Gerät im Standby ist oder nicht.

 3. Was ich nicht auf die schnelle gemacht habe ist den Weg wie die Daten von der io-package jason in die Objekte des Adapters 
 kommen. Ich nehme an das geht über die Admin Oberfläche des Adapters. Das ist jetzt für mich nicht so wild, da ich die Werte ja
 direkt in den Objekten setzten kann und der Aufwand wahrscheinlich nicht so klein ist. 
 Für andere Nutzer ist das vielleicht nicht der schönste Weg.
 
Ich hoffe du störst dich nicht daran, da ich in deinem Code herum gearbeitet habe und siehst es vielleicht als Anregung. 
Danke für deine super Arbeit bisher!

**Comment by Xenon-s** [comment]
Genau der Wert kommt aus dem admin. Da werde ich den auch einbauen, zusätzlich zu den 4 vorhandenen Werten.
Du kannst in Deinem Code machen was Du möchtest 😉 ist ja nur local und auf Deinem System

**Comment by Megawaldi** [comment]
Super. Dann kann ich ja entspannt auf dein nächstes Update warten ;-)

**Comment by Xenon-s** [comment]
Ich habe auch nichts gegen einen PR, mir fehlt aktuell an allen Ecken die Zeit 🤣😉

**Comment by MichaelSchaaf999** [comment]
Hallo,
der Adapter gefällt sehr gut und ist extrem nützlich! Wo ich Probleme habe (die womöglich auch bei mir selber ihre Ursache haben), ist hier...

- Mein Trockner "pumpt", also am Ende geht ja ja in den Status "Ende - Knitterschutz" und dreht die fertig getrocknete Wäsche um, Verbrauch so ca. 197W. Aber da bleibt er dann zwischendurch auch mal stehen und pausiert, da geht die Wattzahl natürlich runter, bis er wieder weiter den Knitterschutz aufnimmt. 
Dein Adapter meint dann, der Trockner sei neu gestartet...
Was kann ich da tun?

- Die eMail-Benachrichtigung funktioniert nicht, es werden keine Mails verschickt. Die Hilfe zur Parametrisierung da sagt ja nicht viel und die Schaltfläche Check-Input antwortet auch nur mit "Input checked" und bringt keinen Fehler.
Was kann ich da verbessern?

Beste Grüße
Michael

michael@schaaf.com

**Comment by Xenon-s** [comment]
@MichaelSchaaf999 bitte eigenes issue erstellen. Sonst geh die Übersicht verloren. Ich antworte dir dann da

**Comment by Megawaldi** [comment]
Hallo Xenon,
ich wollte dich mal auf Stand halten. Nach einigen Tests, habe ich für mich enntdeckt das zwei zusätzliche Werte optimaler sind. Ich arbeite jetzt mit einer einschalt w Zahl und einer ausschalt w Zahl. Das hat den Hintergrund, das ich ab und zu spitzen nach oben oder unten im Verbrauch habe, die dann falsche Stati produziert haben. Die besten Ergebnisse hab ich mit einem möglichst hohen Einschaltwert und einen möglichtst tiefen Ausschaltwert. Werte dazwschen lassen den Status unverändert. Damit fange ich die Spitzen bei abgeschalteten Geräten und die negativen direkt nach dem Waschgang ab. Ich dachte vieleicht interessiert dich das und du denkst mal darauf rum.  Schönen Abend noch.

**Comment by Xenon-s** [comment]
verstehe jetzt nicht ganz was du meinst? Der Adapter arbeitet doch genauso wie du es beschreibst? Dafür sind doch die startvalue, endvalue, etc da? Oder reden wir aneinander vorbei?

![default](https://user-images.githubusercontent.com/65488191/109702246-48b30480-7b94-11eb-9cc0-f8875063f56e.png)

**Comment by Megawaldi** [comment]
Ja wir reden aneinander vorbei ;-). Ich habe jetzt einen wert wann er von "aus" auf "Standby" geht und einen wert wann er von  "Standby" auf "aus" geht. Der selbe Wert für beides hat bei mir zu zu Problemen (falsche States) geführt.

**Comment by Xenon-s** [comment]
nutzt du discord? Vielleicht könnten wir uns da mal treffen und unterhalten :)

**Comment by Megawaldi** [comment]
Gerne am Wochenende vieleicht. Aber ich kann dir kurz schildern was mein Problem war. Mein Trockner z.b läuft mit 2.4-2.8 w wenn er "Aus" ist. Wenn er an geht hat er 14 w. Also könnte ich ja 0.3 als Anschaltwert setzen. Da ich aber ab und zu Spitzen im Verbrauch habe (meistens Nachts, zwischen 0.4-8.0 w) habe die dann den Status "Standby" auslösen würden muss der startwert möglichst hoch sein (14w). Wenn ich aber jetzt den Wert für das ausschalten ebenfalls auf 14w setze schalte der Adapter im Nachlauf wenn der Trockner noch läuft in den Status "Aus". Da fallen die Werte auch mal kurz unter die 14w. Deshalb habe ich den Ausschaltwert möglichst niedrig (0.3w). Das funktioniert super und ich hab immer korrekte States. Ich habe die States bei mir mit kleinen farb Lampen verknüft die je nach State aus oder die Farbe wechseln. Daher sind falsche States bei mir wichtig, um nicht nachts ne Lightshow zu bekommen. Keine Ahnung ob nur ich das Problem sehe. Vieleicht bestrifft es ja noch merere Nutzer.

**Comment by Xenon-s** [comment]
@Megawaldi ioBroker discord: Xenon-s/Steffen#1841

**Comment by Megawaldi** [comment]
Ich schaffe es warscheinlich heute nicht Xenon. Ich melde mich wenn es besser passt...

**Comment by Xenon-s** [comment]
Ja kein Problem, ich schaff es auch nicht. Aber kannst mich da ja anschreiben, sonst spammen wir hier das issue dicht

**Comment by Xenon-s** [comment]
version 1.1.4 hat das integriert, ich warte eine Woche, dann schließe ich das issue
