### ISSUE TITLE
Update issue v3.1.0

### ISSUE THREAD

**Issue by kuckuckmann** [Xenon-s/ioBroker.device-reminder#380]
**Describe the bug**  
At first, with this version Telegramm and mainly e-mail messages are working again :-)
After the update from v3.0.3 to v3.1.0 the adapter startet and stoped in a loop.
Further all devices where deleted.
Configurations for messaging were still avaialble and working.

many thx for the Test Button :-)

**Expected behavior**  
By the update notes it was not expected to loose the configured devices. That is what I would expect, to not loose configuration.

If you need mor details, answer me on a DM at Discord.

**Comment by Xenon-s** [comment]
Pls install github Version 3.1.1

**Comment by Xenon-s** [comment]
The data is not gone, it just hangs and does not finish building the GUI. As long as you do not save, all data is retained. I am already looking for the error myself, but it should actually be fixed with 3.1.1

**Comment by kuckuckmann** [comment]
I Meanwhile uninstalled and reinstalled official v3.1.0 and reconfigured all settings.
I Checked at the Objects, no more devices where listed. So I devided to re-install it.
What is v3.1.1doing better?

**Comment by Xenon-s** [comment]
Version 3.1.1 contains a bugfix, is already on NPM
