### ISSUE TITLE
Alexa message not possible in version 3.1.1 <TypeError: Cannot read properties of undefined (reading 'val

### ISSUE THREAD

**Issue by cooper1988** [Xenon-s/ioBroker.device-reminder#381]
Wenn ich auf Test klicke kommt im Log vom iobroker folgendes:
[messageHandler - error] <TypeError: Cannot read properties of undefined (reading 'val')>

Zeigen tute ich auf
alexa2.0.Echo-Devices.G2A1B505149502QU.Commands.speak

Installiert habe ich alexa.2 und reminder auch die aktuellste Version von github.

Zur Info.
Telegram funktioniert

**Comment by Xenon-s** [comment]
V 3.1.2
