### ISSUE TITLE
Kein Startext eingetragen, dann kommt auch kein Endtext, weder TG noch Alexa

### ISSUE THREAD

**Issue by guergen1** [Xenon-s/ioBroker.device-reminder#382]
Wenn bei den Geräten kein Starttext eingetragen wird, jedoch ein Endtext drin steht, wird weder per Alexa, noch per TG der Endtext ausgegeben.
Steht der Starttext drin, wird dieser, sowie auch der Endtext per Alexa und TG ausgegeben.
[Device-Reminder.txt](https://github.com/Xenon-s/ioBroker.device-reminder/files/14001438/Device-Reminder.txt)

**Comment by Xenon-s** [comment]
V 3.1.2
