### ISSUE TITLE
Update von 1.2.9 auf 3.0.0

### ISSUE THREAD

**Issue by ali86x** [Xenon-s/ioBroker.device-reminder#383]
Hallo zusammen.
Leider habe ich total verpennt, in letzter Zeit den Adapter zu updaten.
Nun ist es ja so, dass man am besten den Adapter bei Version >3.. komplett neu installieren sollte.
Gibt es irgendwie die Möglichkeit, die Einstellungen der Geräte zu speichern bzw diese zu lesen?
Über die Instanzen-Oberfläche wird mir nichts mehr angezeigt (wohl Version echt zu alt).
Ich würde ungerne die ganzen Grenzwerte neu ermitteln müssen :(

**Comment by Xenon-s** [comment]
https://github.com/Xenon-s/ioBroker.device-reminder/issues/326
