### ISSUE TITLE
PathNew Error! [alexa2.0.Echo-Devices.a47ca8ce50b84dcc8a24cxxxxxxxxx.Commands.speak-volume] doesn't exist!

### ISSUE THREAD

**Issue by rewegit** [Xenon-s/ioBroker.device-reminder#385]
When I try to send a test message, I get this error message in the log.
This is also correct because speak-volume does not exist.
Messages to alexa2.o should be sent directly to Commands.speak in the form "volume;text".
e.g. "50;The doorbell rings" 
Here the volume is automatically set to 50 (only for this command).

**Comment by Xenon-s** [comment]
The command has been the same since the adapter was introduced. Is that wrong all of a sudden? Or what exactly is the problem or the wish? 

Issue closed because template was not used and there is no data about your system or the adapter
