### ISSUE TITLE
Feldprüfung

### ISSUE THREAD

**Issue by Klaus-Lucas** [Xenon-s/ioBroker.device-reminder#387]
Adapter 3.1.0:
In `Benutzerdefinierte Gerätetypen` habe ich Wattzahlen mit Nachkommastellen eingegeben.
Die anschließende Prüfung hat sich nicht daran gestört, während die Feldprüfung auf die EIngabe einer Ganzzahl hinweist.

![klu_011](https://github.com/Xenon-s/ioBroker.device-reminder/assets/36620907/093d463d-86aa-421a-9628-c40947e423ee)

**Comment by Xenon-s** [comment]
bitte im Forum lesen, ich schreibe den Adapter gerade neu. Die GUI wird danach in react sein, da tauchen solche Fehler dann nicht mehr auf. 
Auf den hier beschriebenen Fehler habe ich keinen Einfluss

**Comment by mcm1957** [comment]
> Die GUI wird danach in react sein, da tauchen solche Fehler dann nicht mehr auf. Auf den hier beschriebenen Fehler habe ich keinen Einfluss

Randbemerkung:
Wenn ich es richtig mitbekommen habe schreibts du kein REACT UI sondern benutzt die jsonConfig Methode. Auch wenn jsonConfig auf React beruht, bitte die Begriffe trennen,

**Comment by Xenon-s** [comment]
sorry, aber jetzt wirds wirklich albern
