### ISSUE TITLE
Telegram Nachrichten doppelt

### ISSUE THREAD

**Issue by Biker58** [Xenon-s/ioBroker.device-reminder#388]
V 3.1.2
Telegram Nachrichten werden doppelt gesendet.

**Comment by Martin-int01** [comment]
Telegram Nachrichten werden zudem an alle hinterlegten User gesendet, auch wenn diese beim Gerät nicht ausgewählt sind.

**Comment by Martin-int01** [comment]
Seit dem letzten Update funktionieren die Alexa Benachrichtigungen nicht mehr. Beim Senden einer Nachricht kommt folgender Fehler im Log:
PathNew Error! [alexa2.1.Echo-Devices.0894a9df698034fbafaf731d9475c799.Commands.speak-volume] doesn't exists!

**Comment by dawidmpunkt** [comment]
@Xenon-s: 
V 3.1.2: I got the same Issue as @Biker58. Telegram Messages are sent twice. How can this be fixed?

**Comment by jardleex** [comment]
I'm having the issue as well. Version 3.1.2 with two users listed in my telegram instance.

**Comment by w00dst0ck** [comment]
+1

Same for me. Telegram messages are send twice.

**Comment by tetzlav** [comment]
@Xenon-s: Why this issue was closed without any comment or reverence to a commit, but the bug is still present?
