### ISSUE TITLE
Alexa Notifications funktionierten nicht mehr

### ISSUE THREAD

**Issue by Martin-int01** [Xenon-s/ioBroker.device-reminder#389]
Seit dem letzten Update funktionieren die Alexa Benachrichtigungen nicht mehr. Beim Senden einer Nachricht kommt folgender Fehler im Log:
PathNew Error! [alexa2.1.Echo-Devices.0894a9df698034fbafaf731d9475c799.Commands.speak-volume] doesn't exists!

Vielen Dank im Voraus

lg

Martin

**Comment by Xenon-s** [comment]
ich kapier nicht, warum nicht das vorhandene Bug Label genutzt werden kann ... closed
