### ISSUE TITLE
PathNew Error! [0_userdata.0.speak-volume] doesn't exists!

### ISSUE THREAD

**Issue by Streit187** [Xenon-s/ioBroker.device-reminder#398]
This Error comes up because I have activated Alexa Notification but not using the default data point of an Alexa device. This is why the adapter is missing the data point "speak-volume" in same path. 
This should at least not be an error but a warning. 
Maybe it would be good to have a custom notification channel in addition to Alexa, WhatsApp, Telegram and so on or the possibility to deactivate the "set volume" function maybe with giving "0" for volume.

**Comment by RoboCop0815** [comment]
gleiches Probleme
![grafik](https://github.com/Xenon-s/ioBroker.device-reminder/assets/42671266/e38f26e3-8012-4665-b032-317c0411df32)

**Comment by Xenon-s** [comment]
Pls use template, thx

**Comment by Streit187** [comment]
Lol @Xenon-s 👍
