### ISSUE TITLE
Stromverbrauch Trockner während der Schlußphase des Trockners

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Xenon-s/ioBroker.device-reminder#45]
Hallo,
der Adapter gefällt sehr gut und ist extrem nützlich! Wo ich Probleme habe (die womöglich auch bei mir selber ihre Ursache haben), ist hier...

Mein Trockner "pumpt", also am Ende geht ja ja in den Status "Ende - Knitterschutz" und dreht die fertig getrocknete Wäsche um, Verbrauch so ca. 197W. Aber da bleibt er dann zwischendurch auch mal stehen und pausiert, da geht die Wattzahl natürlich runter, bis er wieder weiter den Knitterschutz aufnimmt.
Dein Adapter meint dann, der Trockner sei neu gestartet...
Was kann ich da tun?

Beste Grüße
Michael

michael@schaaf.com

**Comment by Xenon-s** [comment]
Erstmal danke 🙂

Wie hoch sind deine endvalue und endcounter? Je höher der endcounter, desto zuverlässiger das Melde Ergebnis

**Comment by MichaelSchaaf999** [comment]
Sorry, wenn ich dumm frage, aber ich beschäftige mich mit dem Adapter erst seit 2 Stunden: Was sind bzw. wo stehen endvalue und endcounter?

**Comment by Xenon-s** [comment]
Lies ab hier:

https://github.com/Xenon-s/ioBroker.device-reminder/blob/master/README_GER.md#default-devices

**Comment by MichaelSchaaf999** [comment]
Danke sehr: Gelesen.
Waschmaschinen sind anscheinend relativ problemlos "zu erkennen", welchen Status sie haben, wohingegeben Trockner ja mit ihrem "Ende - Knitterschutz" ja eher anders zu betrachten sind.

"starting value" und "final value" scheinen ja Angaben in Watt zu sein: Der guten Ordnung halber könntest Du das vielleicht in den Spaltenüberschriften ergänzen ("W").

"Number of values ´end´" interpretiere ich dann mal so, dass Deine Routinen beim Trockner 50 mal ein Erreichen des end values von beispielsweise 15 W abwarten, bevor sie signalisieren, dass jetzt anscheinend wirklich ein Ende erreicht ist?
Beim Geschirrspüler sogar noch mehr: Im Default stehen da 150: Vermutlich wegen der vielen Pumppausen und auch Heizpausen dieser Geräte.

Heisst: Man muss das für "sein eigenes" Gerät (hier: Trockner) mal ausprobieren, wie lange der beim Durchspielen des Knitterschutzes braucht, bevor er wirklich "Aus" ist? Also welcher Wert bei number-of-values-end sinnvoll ist, um das tatsächliche "Aus" zu erkennen?
Ich weiß auch nicht genau, ob dieser "Knitterschutz" immer gleich / gleich lang / immer in gleichen Intervallen abläuft - diese Frage hat mich bislang ja auch nicht so sehr interessiert.
Spannend.

**Comment by Xenon-s** [comment]
Du kannst dir den average consumption aufzeichnen und schauen welchen Wert er beim tatsächlichen Ende deines Gerätes hat. Es wird immer der average consumption mit deinen Vorgaben abgeglichen. Im average consumption steht immer der errechnete Mittelwert aus dienen Vorgaben

**Comment by MichaelSchaaf999** [comment]
Dies ist der Wert nach Beendigung des Knitterschutzes:
![image](https://user-images.githubusercontent.com/53481090/109799317-2fee3180-7c1c-11eb-9d85-ae8d18bbbe09.png)
Also 3W.

Und dies ist meine Default-Vorgabe:
![image](https://user-images.githubusercontent.com/53481090/109799446-5c09b280-7c1c-11eb-805d-7520be3713cd.png)
Das heisst: Final Value 8W. 

Ist unterschritten, aber es dauert geschätzt fünf Minuten, bis die "Fertig"-Meldung kommt. 
Dann stellt sich mir nur noch die Frage, in welchem Zeitintervall der Adapter diese Werte betrachtet und dann ggfls. auslöst: Sicher nicht im 10-Sekunden-Takt. Aber gibt es hier einen Wert?

**Comment by Xenon-s** [comment]
Doch im 10 Sekunden takt. Je höher du den endwert in W setzt umso höher die Wahrscheinlichkeit von Falschmeldungen. Die Frage ist ja wann du deine Meldung haben willst.
Direkt wenn der knitterschutz anspringt? Dann den wert höher setzen
