### ISSUE TITLE
eMail-Benachrichtigungen

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Xenon-s/ioBroker.device-reminder#46]
Hallo,
der Adapter gefällt sehr gut und ist extrem nützlich! Wo ich Probleme habe (die womöglich auch bei mir selber ihre Ursache haben), ist hier...

Die eMail-Benachrichtigung funktioniert nicht, es werden keine Mails verschickt. Die Hilfe zur Parametrisierung da sagt ja nicht viel und die Schaltfläche Check-Input antwortet auch nur mit "Input checked" und bringt keinen Fehler.
Was kann ich da verbessern?

Beste Grüße
Michael

michael@schaaf.com

**Comment by MichaelSchaaf999** [comment]
Nein, den eMail-Adapter hatte ich nicht richtig eingerichtet, danke für den Hinweis.
Nun funktioniert der: Jetzt teste ich dann mal neu.

**Comment by Xenon-s** [comment]
bitte berichten und issue dann schließen

**Comment by MichaelSchaaf999** [comment]
eMail-Benachrichtigung funktioniert. 
Danke für die Hilfe!
