### ISSUE TITLE
Wann geht der Status der Geräte auf "initialize" und wann geht der wieder weg?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Xenon-s/ioBroker.device-reminder#47]
Ich vermute mal: Beim Start des Adapters geht der Status von Geräten auf "initialize"?
Der scheint dann nach geraumer Zeit wieder den abgefragten Werten zu weichen, also geht dann auf "switched off" oder "standby".
Wenn man das weiß: Dann ist ja gut. Allerdings steht der "initialize" doch recht lange und das könnte ja verwirrend sein.

**Comment by Xenon-s** [comment]
das initialize erscheint beim Adapter start und wenn der Startschwellwert überschritten wird. Wird dann erkannt, dass doch nicht gestartet wurde gehts wieder zurück in standby (wert >1W) oder switched off (Wert < 1 W)
