### ISSUE TITLE
manchmal Speicher Button nicht aktiv nach Änderungen am Alexa Device

### ISSUE THREAD

**Issue by JamesFrosch007** [Xenon-s/ioBroker.device-reminder#48]
**Describe the bug**  
Es ist manchmal nicht möglich die Änderungen zu Speichern, nachdem man unter "Here you can link your devices" das alexa device verändert hat.

**To Reproduce**  
1. In Instanzen gehen
2. Konfiguration wählen
3. "Here you can link your devices" klicken
4. Combobox alexa ändern
5. Speicher Button bleibt inaktiv

**Expected behavior**  
nach jeder Änderung sollten die Speicher Buttons wieder aktiv sein.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

![image](https://user-images.githubusercontent.com/60427607/110980888-a1d62180-8366-11eb-9af0-eef46cfc0b91.png)
![image](https://user-images.githubusercontent.com/60427607/110980957-b9150f00-8366-11eb-8c7e-e1147e748cbb.png)

**Versions:**  
 - Adapter 1.0.6
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: raspian

**Additional context**

**Comment by Xenon-s** [comment]
Danke für das ausführliche issue, ich arbeite gerade an einem größeren Update, ich schau es mir an und bringst dann mit dem nächsten Update raus

**Comment by Xenon-s** [comment]
es gibt eine Alpha Version unter [klick hier](https://github.com/Xenon-s/ioBroker.device-reminder/tree/devTest)

Falls nicht gewünscht, noch etwas gedulden :)

**Comment by Xenon-s** [comment]
version 1.1.4 sollte das Problem beheben. Sonst neues issue
