### ISSUE TITLE
Signal API

### ISSUE THREAD

**Issue by jkbiz** [Xenon-s/ioBroker.device-reminder#57]
Hallo zusammen,

wäre es künftig möglich die Signal API bzw. execute Befehle als "Messenger" Funktion zu nutzen ?

signal-cli -u +***** send -m "Trockner gestartet" -g *****

Besten Dank für die Rückmeldung,

**Comment by Xenon-s** [comment]
kurz und knapp: Ich verstehe nur Bahnhof

**Comment by jkbiz** [comment]
Sorry

Im Adapter habe ich ja die Möglichkeit Messenger zu definieren. Ich setze hier auf Signal.
Leider bietet mir der Adapter keine Signal Schnittstelle an - oder alternativ - eine Möglichkeit einen Befehl auszuführen, statt einer Nachricht.

![message](https://user-images.githubusercontent.com/82655374/115548102-5b4dde00-a2a7-11eb-99f9-f799afce1766.png)

**Comment by Xenon-s** [comment]
Achso meinst du das. Ja etwas unschön ausgedrückt. Adapter gibt's dafür nicht oder? Zumindest konnte ich auf die schnelle nix finden.

Ich hatte geplant, das man demnächst einen beliebigen DP triggern kann. Würde das aktuell reichen?
Im Moment könntest du den Umweg über Script und trigger auf "Status" gehen und dann deine Nachricht absenden

**Comment by jkbiz** [comment]
Nein einen Adapter gibt's nicht, daher hAbe ich bisher alles über Blocky gelöst und für den Benachrichtigungsfall den exec Befehl genutzt und darüber die Signal API angesprochen.
Vielleicht kannst du das ebenfalls abbilden (Feature requests) und ich kann von den Scripten weg ;)

**Comment by Xenon-s** [comment]
@jkbiz Ich bin dabei die Planungen für die Version 2.0 zu machen. Falls du auf dem ioBroker discord unterwegs bist, schreibe mir da doch bitte eine PN oder teile mir deinen Namen mit. Dann kann man sich da unterhalten ;)

**Comment by Xenon-s** [comment]
https://github.com/Xenon-s/ioBroker.device-reminder/issues/195

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen
