### ISSUE TITLE
Wrong typ nach Umstellung auf js-controller 3.3.4

### ISSUE THREAD

**Issue by JBSullivan** [Xenon-s/ioBroker.device-reminder#65]
lt. Community sollen Meldungen die sich aus der Umstellung des js-controller auf die Version 3.3.4 ergeben bei den entsprechenden Adaptern gemeldet werden.

Der Adapter funktioniert Augenscheinlich normla, jedoch wird das LOG mit WARN Meldungen übersäät.

![image](https://user-images.githubusercontent.com/44617472/116776222-9ac6b800-aa67-11eb-9d24-f83b6ad9e640.png)

**Comment by Xenon-s** [comment]
Danke dir ;)

habe gerade die 1.2.1 in die latest geschoben, bitte damit testen und Rückmeldung geben
