### ISSUE TITLE
What about a folder-not-found-error?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Xenon-s/ioBroker.device-reminder#69]
device-reminder.0	2021-05-04 08:01:11.622	error	(1161) Cannot find search "folder" in "system"

Is there any setup or environment missing if the adapter throws this error?

BR
Michael

**Comment by Xenon-s** [comment]
Screenshots log please

**Comment by MichaelSchaaf999** [comment]
<img width="1162" alt="grafik" src="https://user-images.githubusercontent.com/53481090/116968809-82e47380-acb5-11eb-95aa-dfc8d5aaa02c.png">

btw: Adapter was updated, I used it before, without errors.

**Comment by Xenon-s** [comment]
Does the adapter then die completely or does only the error come up and everything runs?

**Comment by MichaelSchaaf999** [comment]
I don't think the adapter is dying, it's still green:
<img width="668" alt="grafik" src="https://user-images.githubusercontent.com/53481090/116970171-c63fe180-acb7-11eb-9e3d-970f5eafd04c.png">

**Comment by Xenon-s** [comment]
Then I need the adapter as well as the js controller version

**Comment by MichaelSchaaf999** [comment]
<img width="281" alt="grafik" src="https://user-images.githubusercontent.com/53481090/116971427-d5279380-acb9-11eb-951f-f04540b9b80a.png">
<img width="282" alt="grafik" src="https://user-images.githubusercontent.com/53481090/116971481-ed97ae00-acb9-11eb-8ce8-0dac166a1f3c.png">

**Comment by Xenon-s** [comment]
Not the Javascript Adapter version, but the version of the JS Controller, which you can find under "Host".
Do you use Telegram or WhatsApp?

**Comment by MichaelSchaaf999** [comment]
Host? 

Eventually this info?
<img width="185" alt="grafik" src="https://user-images.githubusercontent.com/53481090/116975095-5f262b00-acbf-11eb-9804-02742ed31b3b.png">

Or this one fromn 'Übersicht'?
<img width="287" alt="grafik" src="https://user-images.githubusercontent.com/53481090/116975149-76fdaf00-acbf-11eb-9d2e-330755f606bf.png">

**Comment by Xenon-s** [comment]
@MichaelSchaaf999  Do you use Telegram or WhatsApp?
![jsc](https://user-images.githubusercontent.com/65488191/116990449-67886100-acd3-11eb-9152-33b5510a3307.png)

**Comment by MichaelSchaaf999** [comment]
ahyeah: Hosts was not activated, so I searched for it in vain:
<img width="90" alt="grafik" src="https://user-images.githubusercontent.com/53481090/116992972-1da17a00-acd7-11eb-8593-d1e3034f34af.png">

Now it is.

<img width="412" alt="grafik" src="https://user-images.githubusercontent.com/53481090/116993010-2abe6900-acd7-11eb-8027-3a008ac317bb.png">

I understand that this has to be updated, correct?
I only was paying attention to the IOBroker adapters which show up as soon as an update is required (or recommended)

**Comment by Xenon-s** [comment]
But the js controller in version >3.2.16 is still in beta stage. I just wanted to know if you might have already installed the new js controller and that's where the error comes from. More log messages are not coming? I still need the info if you are using telegram or whatsapp. I can't really look for the error otherwise.

**Comment by MichaelSchaaf999** [comment]
sorry, my fault: Using telegam

**Comment by MichaelSchaaf999** [comment]
I did not install the new js controller.
More log messages:
<img width="701" alt="grafik" src="https://user-images.githubusercontent.com/53481090/117099805-6fe3a900-ad72-11eb-9ab5-169154618b70.png">

**Comment by Xenon-s** [comment]
@MichaelSchaaf999 Does the error still occur?

**Comment by MichaelSchaaf999** [comment]
No Sir, device reminder obviously does not throw this error anymore.
So this issue should be closed.
What I do not understand is that another adapter keeps throwing this error: 
<img width="679" alt="grafik" src="https://user-images.githubusercontent.com/53481090/118492610-7a158800-b720-11eb-81c7-9a1d147fe0d5.png">
What's wrong with my IOBroker system? Not a device reminder issue, I know.

**Comment by Apollon77** [comment]
@MichaelSchaaf999 This is not adapter specific. Then something is strange with your system.

which js-controller?

If not at least 3.2.16 then upgrade controller please!!

If 3.2.16: run "iobroker setup first" on cli

FIxed afterwards?

If not: open thread in forum

**Comment by MichaelSchaaf999** [comment]
<img width="459" alt="grafik" src="https://user-images.githubusercontent.com/53481090/118593451-ff904b00-b7a7-11eb-9702-1981dab24240.png">

I will open a thread in the adapter StrathCole/ioBroker.tahoma.
Thx.
