### ISSUE TITLE
No Telegram message content since update

### ISSUE THREAD

**Issue by Kaiman77** [Xenon-s/ioBroker.device-reminder#76]
**Describe the bug**  
Since version 1.2.1 the sending of telegram messages for the "finish" message fails.
Error message:  (1062) Cannot send message [chatId - 1008357771]: Error: ETELEGRAM: 400 Bad Request: message text is empty

In the device reminder configuration an object with the message is used like in the versions before.
The object contains the text to be sent.

Device has been removed and newly created - with the same behavior.

**Versions:**  
 - Adapter version: 1.2.1
 - JS-Controller version: 3.2.16
 - Node version: 12.20.2
 - Operating system: used on Synology docker

**Comment by Xenon-s** [comment]
You're using an extra data point for notification, right? There is also really a text in there when the adapter wants to fetch the notification?

**Comment by Kaiman77** [comment]
yes and yes :-)
It's a string object with a text (being changed by a script regularly).
I just put a fixed text in there for test. I will come back if that works as soon as the washing machine is done.

**Comment by Xenon-s** [comment]
Ok thank you. I haven't actually changed anything that could cause the problem. I'll take a look at it anyway in the days. Currently there is a little bit less time...

**Comment by Kaiman77** [comment]
It works with a fixed text.

If you need further information, just let me know.
No time pressure :-)

**Comment by Xenon-s** [comment]
fixed with V 1.2.3
