### ISSUE TITLE
Meldung wird ausgelöst, wenn sich der State für den Schalter (Switch on/off) ändert

### ISSUE THREAD

**Issue by J-Paul0815** [Xenon-s/ioBroker.device-reminder#8]
Describe the bug
Kein Fehler, sondern ein Vorschlag:
Die Meldung wird ausgelöst, wenn sich der State für den Schalter (Switch on/off) ändert, wenn der 
Energie DP (Path consumption) leer gelassen wird (oder andere Einstellmöglichkeit). 

Expected behavior

Starttext wird ausgelöst, wenn Switch auf true wechselt
Endtext wird ausgelöst, wenn Switch auf false wechselt

**Comment by Xenon-s** [comment]
ich nehme es mal mit auf die Liste auf. Bekommst ne Rückmeldung, wenns drin ist

**Comment by Xenon-s** [comment]
Wir hatten ja schon im discord gesprochen, dass wäre etwas für eine andere Art von Adapter. Hier werde ich es nicht integrieren
