### ISSUE TITLE
Im Info-log wird ein "undefined" für speak-volume ausgegeben

### ISSUE THREAD

**Issue by guergen1** [Xenon-s/ioBroker.device-reminder#88]
Obwohl alles soweit korrekt arbeitet, wird bei einer Sprachausgabe folgende Info-Log Zeile ausgegeben:
`

device-reminder.0 | 2021-06-13 12:22:28.532 | info | undefined is not a valid state value for id "alexa2.0.Echo-Devices.G091EU0704XXX7U3.Commands.speak-volume"
-- | -- | -- | --

`
![grafik](https://user-images.githubusercontent.com/34395245/121803572-9c78c380-cc42-11eb-9d32-ce5113c40d57.png)
 Im Moment habe ich mal zur Fehlereingrenzung den originalen Speak-DP der Alexa genutzt, normal nehme ich den announcment-DP; der LOG-Eintrag ist aber der selbe.
Version: 1.2.1
NPM: 6.14.12
Node.js: 12.22.1
JS-Controller: 3.3.12

**Comment by Xenon-s** [comment]
Wann tritt der Fehler denn genau auf?

**Comment by Xenon-s** [comment]
#75 gleicher Fehler, nur fängt der JS-Controller in diesem Issue den Fehler ab, in dem anderen ist der Controller auf Version 3.1.x

**Comment by guergen1** [comment]
Ah, ok... dann lag ich ja falsch :-)
