### ISSUE TITLE
Erweiterungen

### ISSUE THREAD

**Issue by Xenon-s** [Xenon-s/ioBroker.device-reminder#9]
**Hier werden nur Erweiterungen vom Entwickler eingetragen. Für eigene Ideen bitte ein eignes Issue erstellen!**
**Here only enhancements are entered by the developer. For own ideas please create your own issue!**

- boolean DPs einfügen, damit leichter in VIS auf Statusänderungen reagiert werden kann **(V 0.6)** [&check;]

- Zustandsmeldungen frei konfigurierbar machen **(V 0.6)** [&check;]

- weitere Messenger prüfen 
   - pushover in V 1.0 [&check;]
   - email in V 1.0 [&check;]
   - signal -> aktuell kein Adapter vorhanden, exec befehl?

- Schwellwert Standby einfügen -> V 1.2.1 [&check;]
- Laufzeitüberwachung -> V 1.2.1 [&check;]
- letzte Laufzeit: 
   - als DP -> V 1.2.1 [&check;]
   - als JSON -> V 1.2.1 [&check;]
- Sprachassistenten Ansage im Loop V1.4 [geplant ] -> Wird in V 2.0 implementiert
- Anwesenheitserkennung -> V1.3 [geplant] -> Wird in V 2.0 implementiert

**Comment by Ceel84** [comment]
Stromverbrauchsberechnung in kw und Euro inkl. Mitteilung per Telegram, Whatsapp, ...

**Comment by Xenon-s** [comment]
> Stromverbrauchsberechnung in kw und Euro inkl. Mitteilung per Telegram, Whatsapp, ...

Nein, das wird definitiv nicht kommen. Ist im forum auch schon zu genüge erklärt worden. Dafür stehen Datenpunkte und Laufzeiten bereit um sich ein extra Script zu bauen
